# Exterior measure, σ-algebra

<span style="color:green">
What are the measures of boundaries? 

Are measures preserved under closures and interiors?

How to establish additivity when one of the sets is open, or closed?
</span>

First recall some topological definitions:

1. A **point** $x=(x_j)\in \R^d$ consists of $d$ real-numbers. 
2. The **norm** $|x|$ of $x$ equals $(\sum x_j^2)^{1/2}$.
3. The **distance** between two points is is $|x-y|$. 
4. The **distance** between two sets is $d(E, F)=\inf|x-y|$. 
5. A set $E$ is **bounded** if it is contained in some ball of finite radius. 
6. A bounded set is **compact** if it is also closed. 
7. A point $x$ is a **limit point** of the set 
$E$ if $\forall r>0, B_r(x)\cap E\neq \emptyset$. 
8. $x\in E$ is **isolated** if $\exists r>0: B_r(x)\cap E=\{x\}$. 
9. $x\in E$ is an **interior** point if $\exists r>0: B_r(x)\subset E$. 
10. The **boundary** $\partial E = \bar E - \mrm{Int}(E)$. 
11. A closed set $E$ is **perfect** if it does not have any isolated points. 

Organization: 

1. Our first attempt at defining a measure is: 
    We can partition any shape into the countable union of closed cubes, 
    for each of which we individually know how to measure. However, 
    it is not immediately apparant that this measure is independent 
    of our choice of partition. 
2. To formalize the intuition, we introduce the exterior measure, which 
    is the smallest "cover" of the object by closed cubes. We 
    show that it satisfies _monotonicity_ and _countable subadditivity_ 
    and agrees with our initial definition. 
3. However, there are disjoint sets on which the exterior measure is not 
    additive. In fact, one can show that there exists no additive measure 
    on all subsets of $\R$. This motivates us to introduce the $\sigma$-algebra, 
    as well as the Borel set, which formalizes the notion of 
    "well-behaved subsets of $\R^n$". 

Remarks: 

1. $\sigma$-algebras are closed under countable 
    elementary set operations (complement, union, intersection), 
    all of which commute with function pre-images.
2. The Borel algebra is freely generated by open sets. To show 
    measurability it suffices to show that preimages of generators. 
3. $\sigma$-algebra and Borel sets are so defined so that measurability is 
    compatible with composition, limits, $\sup$, $\inf$, 
    as well as implied by continuity (and semi-continuity). 
4. Monotone class theorem: the transfinite construction of 
    a freely generated $\sigma$-algebra is simplified as 
    the monotone limit of the freely generated algebra. 

## Initial attempt at defining a measure {-}

:::{.definition name="closed rectangle"}
A rectangle $R$ in $\R^d$ is of the form 
\[ 
    R = \prod_{j=1}^d [a_j, b_j], \quad a_j\leq b_j\in \R 
\] 
Its volume is $|R| = \prod (b_j-a_j)$. An open rectangle 
consists of open intervals. A union of rectangles is **almost disjoint** 
if the interiors are disjoint. 
:::

:::{.lemma}
If a rectangle is the almost-disjoint union of 
finitely many other rectangles $R=\bigcup_{k=1}^N R_k$, then 
\[ 
    |R| = \sum_{k=1}^N |R_k| 
\] 
:::
_Proof:_ Consider the grid formed by extending indefinitely 
the sides of all rectangles. This yields finitely many 
rectangles $(\tilde R_j)_{1\leq j\leq M}$ and a partition 
$J_1, \cdots, J_n$ of the integers between $1$ and $M$ such that 
\[ 
    R = \bigcup_{j=1}^M \tilde R_j, \quad 
    R_k = \bigcup_{j\in J_k} \tilde R_j, \quad k\in [N]
\] 
This finer grid partitions the sides of $R$, so 
\[ 
    |R| = \sum_{j=1}^M |\tilde R_j| = \sum_{k=1}^N \sum_{j\in J_k}|\tilde R_j| 
    = \sum_{k=1}^N |R_k| 
\] 
This extends to the following lemma:

:::{.lemma}
Given rectangles $R, R_1, \cdots, R_N$ such that 
$R\subset \bigcup_{k=1}^N R_k$, then 
\[ 
    |R| \leq \sum_{k=1}^N |R_k| 
\] 
:::

:::{.theorem}
Every open subset $\mca O$ of $\R$ can be written uniquely as a 
countable union of disjoint open intervals. 
:::
_Proof_ For each $x\in \mca O$, let $I_x$ be the largest interval 
containing $x$, in turn contained in $\mca O$ 
\[ 
    I_x = (a_x, b_x), \quad a_x = \inf\{a<x: (a, x)\subset \mca O\}, 
    \quad b_x = \sup\{b>x:(x, b)\subset \mca O\}
\] 
Then $O = \bigcup_x I_x$. The collection $\mca I = \{I_x\}_{x\in \mca O}$ 
must be disjoint (if they overlap they must be equal). There are 
countably many countably many distinct intervals: every distinct 
interval contains a distinct rational number, and there are only 
countably many rational numbers. 


:::{.theorem #openSetCubeDecomposition 
name="an open set is a countable union of almost-disjoint cubes"}
Every open subset $\mca O$ of $\R^{d\geq 1}$ is a countable union 
of almost disjoint closed cubes. 
:::
_Proof:_ Consider a grid $\mca Q_0$ in $\R^d$ formed by taking all closed 
cubes of side length $1$. We accept a cube $Q$ only if $Q\subset \mca O$, 
tentatively accept it if $\mca O, \mca O^c$ both intersect 
$Q$, and reject if $Q\subset \mca O^c$. 
We can inductively partition the tentatively accepted cubes. 
This procedure is repeated indefinitely, and the resulting 
collection $\mca Q$ of accepted cubes is countable
and consists of almost disjoint cubes. 
To see why the resulting set is countable, each grid can be 
indexed by stage-number and its index in the stage, and 
both are finite. Their union is $\mca O$: 
given $x\in \mca O$ there is a cube of side length $2^{-N}$, for some $N$, 
that contains $x$ and is entirely contained in $\mca O$. 

:::{.remark}
This is an interesting construction which coincides with our 
intuition. However, the decomposition of $\mca O$ into countable union 
of disjoint open intervals is not unique, and it is nonapparant that 
the "volume" defined by each are equivalent. Instead, we can define 
measure in terms of the inf of covering cubes, then demonstrate equivalence 
with the definition above. See proposition \@ref(prp:unionCoverEquivalence). 
:::

## The exterior measure {-}

:::{.definition name="exterior measure"}
The exterior measure $\mu_*(E)$ of any subset $E\subset \R^d$ is 
\[ 
    \mu_*(E) = \inf \sum_{j=1}^\infty |Q_j|
\] 
where the $\inf$ is over all countable coverings of $E$ by 
closed rectangles. 
:::

:::{.proposition name="monotonicity"}
$E_1\subset E_2\implies \mu_*(E_1)\leq \mu_*(E_2)$ 
:::
_Proof:_ Every covering of $E_2$ by a countable set of cubes 
is also a covering of $E_1$. 

:::{.proposition #countableSubAdd name="countable sub-additivity"}
$E=\bigcup_{j=1}^\infty E_j\implies \mu_*(E)\leq \sum_{j=1}^\infty \mu_*(E_j)$ 
:::
_Proof:_ Idea is to construct increasingly tight open covers such that 
the countable union of these covers is still finitely tight. 
Assume the nontrivial case $\mu_*(E_j)<\infty$. 
For every $\epsilon>0$, we can construct for each $j$ a covering 
\[ 
    E_j\subset \bigcup_{k=1}^\infty Q_{k, j}, \quad 
    \sum_{k=1}^\infty |Q_{k, j}| \leq \mu_*(E_j) + \df{\epsilon}{2^j}
\] 
The increasingly tight bound ensures that 
\begin{align}
    \mu_*(E) 
    &\leq \sum_{j, k}|Q_{k, j}| \leq \sum_{j=1}^\infty \mu_*(E_j) + \df \epsilon {2^j} 
    = \sum_{j=1}^\infty \mu_*(E_j)+\epsilon
\end{align}

:::{.proposition name="equivalence with open cover infimum"}
Given $E\subset \R^d$, $\mu_*(E)=\inf \mu_*(\mca O)$, where $\inf$ is 
over all open sets $\mca O$ covering $E$. 
:::
_Proof:_ $\mu_*(E)\leq \inf \mu_*(\mca O)$ holds by monotonicity. 
For the other direction, choose cubes $Q_j$ covering $E$ 
with margin $\epsilon/2$, and for each cube choose open cube 
$O_j$ covering $Q_j$ with margin $\epsilon/2^{j+1}$, then $(O_j)$ 
cover $E$ with margin $\epsilon$. 

:::{.proposition name="additivity with finite distance"}
If $E=E_1\cup E_2$ and $d(E_1, E_2)>0$, then 
\[ 
    \mu_*(E) = \mu_*(E_1)+\mu_*(E_2) 
\] 
:::
_Proof:_ By subadditivity, $\mu_*(E)\leq \mu_*(E_1)+\mu_*(E_2)$. 
To show the converse, select $0<\delta < d(E_1, E_2)$ and 
choose a cover $(Q_j)$ of $E$ by closed cubes with margin $\epsilon$. 
Subdivide $(Q_j)$ so that each has size less than $\delta$, so 
that each cube intersects at most one of $E_1, E_2$. Denote by 
$J_1, J_2$ the indices for which $Q_j$ intersects $E_1, E_2$, then 
$E_1, E_2$ are covered by $Q_{J_1}, Q_{J_2}$ respectively. 

:::{.proposition #unionCoverEquivalence name="equivalence with intuitive definition"}
If $E$ is the countable union of almost disjoint cubes $\{Q_j\}$, then 
\[ 
    \mu_*(E) = \sum_{j=1}^\infty |Q_j| 
\] 
:::
The forward direction $\mu_*(E)\leq \cdots$ follows from 
countable sub-additivity \@ref(prp:countableSubAdd). 
For the other direction, for arbitrary $\epsilon>0$, construct 
for each cube $Q_j$ a sub-cube $\tilde Q_j\subsetneq Q_j$ such that 
$|Q_j| \geq |\tilde Q_j|-\epsilon/2^j$, then $\{\tilde Q_j\}$ 
are fully disjoint and the following holds for all $\epsilon$: 
\[ 
    \mu_*\left(\bigcup \tilde Q_j\right) = \sum_{j=1}^\infty |Q_j| - \epsilon 
    \leq \mu_*(E)
\] 

## σ-algebra, monotone class theorem {-}

:::{.definition #setAlgebra name="algebra of sets"}
A collection $\mca A$ of sets is an algebra 
of sets if it is closed under finite union and 
differences: 
\[ 
    A, B\in \mca A\implies A\cup B, A-B, B-A\in \mca A 
\] 
:::

:::{.definition name="σ-algebra"}
Given a set $X$, $\mca S\subset 2^X$ is a $\sigma$-algebra on $X$ if: 

1. $\emptyset\in \mca S$. 
2. Closure under complement: $E\in \mca S\implies X-E\in \mca S$. 
3. Closure under countable union: 
    $\{E_j\}\in \mca S\implies \bigcup_{k=1}^\infty E_k \in \mca S$. 
:::

:::{.proposition name="derived properties of σ-algebras"}
Given a $\sigma$-algebra $\mca S$ on $X$, then 

1. $X\in \mca S$. 
2. Closure under finite union, intersection, and difference: 
\[ 
    D, E\in \mca S\implies D\cup E, D\cap E, D-E\in \mca S 
\] 
3. $E_1, \cdots\in \mca S\implies \bigcap_{k=1}^\infty E_k \in \mca S$
:::
_Proof:_ (1) follows from $X=X-\emptyset$. 
(2) follows from $D\cap E = (X-D)\cup (X_E)$ and $D-E=(D\cap E)\cup E$. 
(3) follows from $\bigcap_{k=1}^\infty E_k = X - \bigcup_{k=1}^\infty (X-E_k)$. 

:::{.example}
Given any set $X$, both $\{\emptyset, X\}$ and $2^X$ are $\sigma$-algebras 
on $X$. The set of all subsets $E$ such that $E$ 
is countable or $X-E$ countable is a $\sigma$-algebra (countable 
union of countable set is countable, else if one element's complement 
is countable, then the union's complement is countable, too). 
:::

:::{.remark}
A $\sigma$-algebra on $X$ is a subset of $2^X$ that contains $\emptyset$ 
and is closed under countable union. Compare to a topology on $X$, which 
is a subset of $2^X$ that contains $\emptyset, X$, and is closed under 
arbitrary unions and finite intersections. 
:::

:::{.definition name="measurable space, measurable set"}
A measurable space is a pair $(X, \mca S)$ where $\mca S$ is a $\sigma$-algebra 
on $X$. 
$S\subset X$ is $\mca S$-measurable iff $S\in \mca S$. 
:::

:::{.proposition name="freely generated σ-algebra"}
Given a set $X$ and $\mca A\subset 2^X$, the intersection 
of all $\sigma$-algebras $\mca S$ on $X$ such that 
$\mca A\subset \mca S$ is a $\sigma$-algebra on $X$. 

In other words, every subset $A\subset 2^X$ freely generates 
a $\sigma$-algebra $\sigma_{\mrm{Alg}}(A)$ on $X$.
:::
_Proof:_ There is at least one $\sigma$-algebra $\mca S=2^X$ 
containing $\mca A$. Let $\mca S$ be the intersection, then 
$\emptyset\in \mca S$; the other two properties 
are well-behaved under intersection. 

:::{.definition #productSigmaAlg name="product σ-algebra"}
The product $\sigma$-algebra is the smallest 
$\sigma$-algebra containing all rectangles. 
\[ 
    \Sigma = \sigma_{\mrm{Alg}}(\Sigma_1\times \Sigma_2) 
    = \sigma_{\mrm{Alg}}\left(\{
        A_1\times A_2 | A_1\in \Sigma_1, A_2\in \Sigma_2
    \}\right)
\] 
where here $\Sigma_1\times \Sigma_2$ denotes the Cartesian 
product of sets. The product measure $\mu = \mu_1\times \mu_2$ is 
:::


:::{.proposition name="section property of product algebra"}
The product $\sigma$-algebra $\Sigma = \Sigma_1\times \Sigma_2$ 
has the **section property**: $\forall A\in \Sigma$ and 
define 
\[ 
    A_1(x_2)\in \Omega_1 = \{x_1\in \Omega_1: (x_1, x_2)\in A\}
\] 
then $A_1(x_2)\in \Sigma_1$ for every choice of $x_2$. 
:::
_Proof:_ The set $\Sigma'$ of all subsets of $\Omega_1\times \Omega_2$ 
(regarded as Cartesian product of sets) 
satisfying the section property is a $\sigma$-algebra containing 
$\Sigma_1\times \Sigma_2$; the proof concludes by the universal 
property of $\Sigma_1\times \Sigma_2$. 

:::{.definition name="monotone class"}
A monotone class $\mca M$ is a set of sets with the following 
properties: 
\begin{align}
    A_1, \cdots \in \mca M, \quad A_j\nearrow A &\implies A\in \mca M \\ 
    A_1, \cdots \in \mca M, \quad A_j\searrow A &\implies A\in \mca M
\end{align}
:::

:::{.theorem #monotoneClassTheorem name="monotone class theorem"}
Given a set $\Omega$ and an algebra (definition \@ref(def:setAlgebra))
of subsets of $\Omega$ such that $\Omega, \emptyset\in \mca A$. 
Then the smallest monotone class $\mca S$ containing $\mca A$ 
is equal to $\sigma_{\mrm{Alg}}(\mca A)$. 
:::
_Proof:_ The smallest monotone class $\mca M$ containing $\mca A$ 
is the intersection of all monotone classes containing $\mca A$. 
Now, if $\mca S$ is closed under complement and finite unions, 
then for any $A_1, \cdots$, the sequence 
\[ 
    \left(B_j = \bigcup_{k=1}^j A_j \in \mca M\right) \nearrow
    \bigcup_{j=1}^\infty A_j \in \mca M 
\] 
Together with complements, this will show that $\mca M$ is a $\sigma$-algebra; 
then $\mca M$ is the minimal $\sigma$-algebra since every 
$\sigma$-algebra is a monotone class. To show that $\mca M$ 
is indeed closed under complement and finite union, argue for 
every set $A\in \mca M$ that the set $C(A)$ of all sets which 
stays within $\mca M$ under complement (or union) is a 
monotone class; by the algebraic property of $\mca A$ we have 
$A\in C(A)\subset C(A)=\mca M$, which shows that $A$ is 
closed under complement and finite union. 

## Disjoint additivity on Borel sets {-}

We will next show that the exterior measure is additive 
on Borel sets. 

:::{.definition name="Borel subset, Borel set"}
The smallest $\sigma$-algebra on $\R^n$ containing all 
open subsets of $\R^n$ is the collection of Borel subsets. 
This $\sigma$-algebra is called the Borel set. 
\[ 
    \mca B = \sigma_{\mrm{Alg}}(\text{open intervals})
\] 
:::

:::{.lemma name="invariance of outer-measure under interior and closure"}
For any set $A$, $\mu_*(A) = \mu_*(\mrm{Int}(A)) = \mu_*(\bar A)$. 
:::
_Proof:_ For every $\epsilon>0$, we can (resp. expand) each element of the 
cover for $A$ by $\epsilon/2^j$ so that they cover $

:::{.lemma name="additivity conditions for outer measure"}
Let $A$ and $G$ be disjoint subsets of $\R^n$, then 
$\mu_*(A\cup G) = \mu_*(A) + \mu_*(G)$ if $G$ is open or closed. 
:::
<span style="color:red">
TODO
</span>

:::{.theorem name="additivity of outer measure if one of the sets is a Borel set"}
Given $B\in \mca B$ and arbitrary $A$, then 
\[ 
    \mu_*(A\sqcup B) = \mu_*(A)+\mu_*(B)
\] 
:::
_Proof:_ Choose a closed $\epsilon$-coveree of $B$ so 
$|B-(F\subset B)|<\epsilon$, then 
\[ 
    \mu_*(A\sqcup B)
    \geq \mu_*(A) + \mu_*(F)
    = \mu_*(A) + \mu_*(B) - \mu_*(B-F) 
    \geq \mu_*(A) + \mu_*(B) - \epsilon 
\] 
The other direction follows from countable additivity. 