# Measures on $\R^n$ {#realMeasures}

Organization: 

1. The exterior measure is the smallest "cover" of the object by closed cubes. We 
    show that it satisfies _monotonicity_ and _countable subadditivity_ 
    and agrees with our initial definition. 
2. However, there are disjoint sets on which the exterior measure is not 
    additive. One can show that there exists no additive measure 
    on all subsets of $\R$. This motivates us to introduce the $\sigma$-algebra, 
    as well as the Borel set, which formalizes the notion of 
    "well-behaved subsets of $\R^n$". 
2. The Lebesgue measure is simply the exterior measure 
    on Borel sets of $\R^n$. 

First recall some topological definitions:

1. A **point** $x=(x_j)\in \R^d$ consists of $d$ real-numbers. 
2. The **norm** $|x|$ of $x$ equals $(\sum x_j^2)^{1/2}$.
3. The **distance** between two points is is $|x-y|$. 
4. The **distance** between two sets is $d(E, F)=\inf|x-y|$. 
5. A set $E$ is **bounded** if it is contained in some ball of finite radius. 
6. A bounded set is **compact** if it is also closed. 
7. A point $x$ is a **limit point** of the set 
$E$ if $\forall r>0, B_r(x)\cap E\neq \emptyset$. 
8. $x\in E$ is **isolated** if $\exists r>0: B_r(x)\cap E=\{x\}$. 
9. $x\in E$ is an **interior** point if $\exists r>0: B_r(x)\subset E$. 
10. The **boundary** $\partial E = \bar E - \mrm{Int}(E)$. 
11. A closed set $E$ is **perfect** if it does not have any isolated points. 

## Exterior measure {-}

:::{.definition name="exterior measure"}
The exterior measure $\mu_*(E)$ of any subset $E\subset \R^d$ is 
\[ 
    \mu_*(E) = \inf \sum_{j=1}^\infty |Q_j|
\] 
where the $\inf$ is over all countable coverings of $E$ by 
closed rectangles. 
:::

:::{.proposition name="monotonicity"}
$E_1\subset E_2\implies \mu_*(E_1)\leq \mu_*(E_2)$ 
:::
_Proof:_ Every covering of $E_2$ by a countable set of cubes 
is also a covering of $E_1$. 

:::{.proposition #countableSubAdd name="countable sub-additivity"}
$E=\bigcup_{j=1}^\infty E_j\implies \mu_*(E)\leq \sum_{j=1}^\infty \mu_*(E_j)$ 
:::
Proof idea: construct increasingly tight open covers such that 
the countable union of these covers is still finitely tight. 
<details>
<summary>Proof</summary>
Assume the nontrivial case $\mu_*(E_j)<\infty$. 
For every $\epsilon>0$, we can construct for each $j$ a covering 
\[ 
    E_j\subset \bigcup_{k=1}^\infty Q_{k, j}, \quad 
    \sum_{k=1}^\infty |Q_{k, j}| \leq \mu_*(E_j) + \df{\epsilon}{2^j}
\] 
The increasingly tight bound ensures that 
\begin{align}
    \mu_*(E) 
    &\leq \sum_{j, k}|Q_{k, j}| \leq \sum_{j=1}^\infty \mu_*(E_j) + \df \epsilon {2^j} 
    = \sum_{j=1}^\infty \mu_*(E_j)+\epsilon
\end{align}
</details>

:::{.proposition name="equivalence with open cover infimum"}
Given $E\subset \R^d$, $\mu_*(E)=\inf \mu_*(\mca O)$, where $\inf$ is 
over all open sets $\mca O$ covering $E$. 
:::
<details>
<summary>Proof</summary>
$\mu_*(E)\leq \inf \mu_*(\mca O)$ holds by monotonicity. 
For the other direction, choose cubes $Q_j$ covering $E$ 
with margin $\epsilon/2$, and for each cube choose open cube 
$O_j$ covering $Q_j$ with margin $\epsilon/2^{j+1}$, then $(O_j)$ 
cover $E$ with margin $\epsilon$. 
</details>

:::{.proposition name="additivity with finite distance"}
If $E=E_1\cup E_2$ and $d(E_1, E_2)>0$, then 
\[ 
    \mu_*(E) = \mu_*(E_1)+\mu_*(E_2) 
\] 
:::
<details>
<summary>Proof</summary>
By subadditivity, $\mu_*(E)\leq \mu_*(E_1)+\mu_*(E_2)$. 
To show the converse, select $0<\delta < d(E_1, E_2)$ and 
choose a cover $(Q_j)$ of $E$ by closed cubes with margin $\epsilon$. 
Subdivide $(Q_j)$ so that each has size less than $\delta$, so 
that each cube intersects at most one of $E_1, E_2$. Denote by 
$J_1, J_2$ the indices for which $Q_j$ intersects $E_1, E_2$, then 
$E_1, E_2$ are covered by $Q_{J_1}, Q_{J_2}$ respectively. 
</details>

:::{.proposition #unionCoverEquivalence name="equivalence with intuitive definition"}
If $E$ is the countable union of almost disjoint cubes $\{Q_j\}$, then 
\[ 
    \mu_*(E) = \sum_{j=1}^\infty |Q_j| 
\] 
:::
<details>
<summary>Proof</summary>
The forward direction $\mu_*(E)\leq \cdots$ follows from 
countable sub-additivity \@ref(prp:countableSubAdd). 
For the other direction, for arbitrary $\epsilon>0$, construct 
for each cube $Q_j$ a sub-cube $\tilde Q_j\subsetneq Q_j$ such that 
$|Q_j| \geq |\tilde Q_j|-\epsilon/2^j$, then $\{\tilde Q_j\}$ 
are fully disjoint and the following holds for all $\epsilon$: 
\[ 
    \mu_*\left(\bigcup \tilde Q_j\right) = \sum_{j=1}^\infty |Q_j| - \epsilon 
    \leq \mu_*(E)
\] 
</details>

## Measurable functions on $\R^n$ {#realMeasurableFunctions -}
:::{.proposition name="measurable function"}
Given a measurable space $(\Omega, \Sigma)$. A function 
$\Omega\to \R^n$ is $\Sigma$-measurable if 
$f^{-1}(B) \in \Sigma$ 
for every Borel set $B\subset \R^n$. 
:::

:::{.example}
If $\Sigma=\{\emptyset, \Omega\}$, then the only $\Sigma$-measurable 
functions from $\Omega\to \R^n$ are constant functions. On the 
other extreme, if $\Sigma=2^\Omega$, then every function is measurable. 
For a nontrivial example, if $\Sigma=\{\emptyset, (-\infty, 0), [0, \infty), \R\}$ 
then $f:\R\to \R$ is measurable iff it is 
constant on $(-\infty, 0), [0, \infty)$. 
:::

:::{.definition name="characteristic function"}
Given $E\subset \Omega$, the characteristic function $\chi_E:\Omega\to \R$ is 
\[ 
    \chi_E(x) = \begin{cases}
        1 & x\in E \\ 
        0 & x\notin E
    \end{cases}
\] 
:::

:::{.proposition name="property of characteristic function"}
Given $(\Omega, \Sigma), E\subset \Omega$, then $\chi_E$ is $\Sigma$-measurable 
iff $E\in \Sigma$. 
:::
_Proof:_ 
$\chi_E^{-1}(B) = \{E, \Omega-E, \Omega, \emptyset\}$ 
depending on how $B\subset \R$ intersects with $\{0, 1\}$. 

:::{.proposition name="continuity implies Borel measurability"}
Every continuous function $f:\Omega\to \R^n$ defined on 
a Borel subset $\Omega\subset \R^m$ is a Borel-measurable function. 
:::
_Proof:_ Consider the preimage of $x>a$ ($x, a\in \R^n$ and inequality 
holds elementwise). For any such $a$, consider 
\[ 
    f^{-1}(x>a) 
    = \left[\bigcup_{x\in f^{-1}(x>a)} (x-\delta_x, x+\delta_x) \right]\cap \Omega
\] 
Given every $x\in \R^m: f(x)>a$, by continuity $\exists \delta_x\in \R$ 
such that $f((x-\delta_x, x+\delta_x))>a$. The term in the paranthesis 
is an open set, hence its intersection with the Borel set $\Omega$ is Borel. 

$f:(\Omega\subset \R)\to \R$ is increasing if $x < y\implies f(x)\leq f(y)$; 
it is monotonic if $f$ or $-f$ is increasing. 

:::{.proposition}
if $f:\Omega\to \R$ is monotonic and $\Omega$ is Borel, then $f$ is measurable. 
:::
_Proof:_ Fix $a\in \R$, then for $b=\inf f^{-1}((a, \infty))$, 
monotonicity implies 
\[ 
    f^{-1}((a, \infty)) = (b, \infty)\cap \Omega 
    \text{ or }
    [b, \infty)\cap \Omega
\] 

:::{.proposition name="preservation of measurability under limits"}
Suppose $\{f_j\}\to f:(\Omega, \Sigma)\to \R^n$ point-wise each $f_j$ 
is $\Sigma$-measurable, then $f$ is $\Sigma$-measurable. 
:::
_Proof:_ Unrolling the definition of the limit: for any 
$x\in \Omega, a\in \R^n$, $f(x)>a$ iff 
\begin{align}
    & \lim_{k\to \infty} f_k(x) > a \\ 
    \iff & \exists j>0, \exists N: f_{\forall k>N}(x)>a+1/j \\ 
    \iff & x\in \bigcup_{j=1}^\infty 
        \bigcup_{N=1}^\infty 
        \bigcap_{k=1}^\infty f_k^{-1}(y>a+1/j)
\end{align}
Note that we only need some $j$ to exist. Each $\exists$ translates 
to $\bigcup$, and each $\forall$ translates to $\bigcap$. Then 
the preimage of $y>a$ the measurable set above. 

:::{.definition name="extended Borel"}
$A\subset [-\infty \infty]$ is a Borel set if $A\cap \R$ is Borel. 
Extended measurability is defined similarly. 
:::

:::{.theorem name="variational limits are measurable"}
Given measurable $\{f_k: (\Omega, \Sigma)\to \R\}$, the following functions 
are also measurable: 
\[ 
    g(x) = \inf_k f_k(x), \quad h(x) = \sup_k f_k(x)
\] 
:::
_Proof:_ It suffices to verify for the $\sup$ case that 
\begin{align}
    h(x) > a &\implies \exists k: f_k(x) > a \\ 
    h^{-1}((a, \infty]) &= \bigcup_{k=1}^\infty f_k^{-1}((a, \infty])
\end{align} 

:::{.proposition name="a.e. measurability"}
Given $f$ measurable and $f=g$ a.e. (they differ on a set of 
measure $0$ on the domain), then $g$ is measurable. 
:::
_Proof:_ Let $\{\mca A\}$ be a subbasis generating the measurable  
sets, then $\forall A\in \mca A$, the symmetric difference of 
pre-images $f^{-1}(A), g^{-1}(A)$ is dominated by a set of 
measure $0$; by measurability $g^{-1}(A)$ is measurable, 
so $f^{-1}(S)$ is also measurable. 

Some notations are convenient: 

:::{.definition #setSequenceNotation name="sequence of sets"}
An increasing sequence of sets $\{A_n\}$ is a sequence 
\[ 
    A_1\subset A_2\subset \cdots \to A = \bigcup_{n=1}^\infty A_n
\] 
also written $A_j\nearrow A$. Similarly, a decreasing 
sequence of sets is written $A_j\searrow A$. 
\[ 
    A_1\supset A_2\supset \cdots \to A = \bigcap_{n=1}^\infty A_n 
\] 
:::

## Disjoint additivity on Borel sets {-}

We will next show that the exterior measure is additive 
on Borel sets. 

:::{.definition name="Borel subset, Borel set"}
The smallest $\sigma$-algebra on $\R^n$ containing all 
open subsets of $\R^n$ is the collection of Borel subsets. 
This $\sigma$-algebra is called the Borel set. 
\[ 
    \mca B = \sigma_{\mrm{Alg}}(\text{open intervals})
\] 
:::

:::{.lemma name="invariance of outer-measure under interior and closure"}
For any set $A$, $\mu_*(A) = \mu_*(\mrm{Int}(A)) = \mu_*(\bar A)$. 
:::
_Proof:_ For every $\epsilon>0$, we can (resp. expand) each element of the 
cover for $A$ by $\epsilon/2^j$ so that they cover $

:::{.lemma name="additivity conditions for outer measure"}
Let $A$ and $G$ be disjoint subsets of $\R^n$, then 
$\mu_*(A\cup G) = \mu_*(A) + \mu_*(G)$ if $G$ is open or closed. 
:::
<span style="color:red">
TODO
</span>

:::{.theorem name="additivity of outer measure if one of the sets is a Borel set"}
Given $B\in \mca B$ and arbitrary $A$, then 
\[ 
    \mu_*(A\sqcup B) = \mu_*(A)+\mu_*(B)
\] 
:::
_Proof:_ Choose a closed $\epsilon$-coveree of $B$ so 
$|B-(F\subset B)|<\epsilon$, then 
\[ 
    \mu_*(A\sqcup B)
    \geq \mu_*(A) + \mu_*(F)
    = \mu_*(A) + \mu_*(B) - \mu_*(B-F) 
    \geq \mu_*(A) + \mu_*(B) - \epsilon 
\] 
The other direction follows from countable additivity. 

## Lebesgue Measure {-}

:::{.definition name="Lebesgue measurable sets"}
The set $\mca L$ of sets which are $\epsilon$-approximable from below by closed 
sets are called Lebesgue measurable sets. 
:::

:::{.proposition name="properties of Lebesgue measurable sets"}
$\mca B\subset \mca L$, and $\mca L$ is a $\sigma$-algebra. 
:::
_Proof:_ Note that $\mca L$ contains all closed sets, 
we just need to show that $\mca L$ is a $\sigma$-algebra: 
by taking complements we will show that it contains all open sets. 
Proof is by standard argument, omitted. 

<span style="color:green">
In particular, this shows that every Lebesgue-measurable set is almost 
Borel: i.e. there exists a Borel set which differs from it by a 
set of measure $0$. 
</span>

:::{.definition name="Lebesgue measurable set"}
$A\subset \R^n$ is Lebesgue measurable if it is almost a 
Borel set, i.e. $\exists B\in \mca B$ such that $B\subset A, \mu_*(A-B)=0$. 
:::


:::{.remark name="distinction between subset and unions"}
Let $\mca C$ denote the Cantor set, then $\mca C/2 + \mca C/2=[0, 1]$. 
This does not contradict subadditivity 
because sumsets are in general much larger than unions. 
:::

:::{.theorem #measurableCharacterization 
    name="characterization of Lebesgue measurable sets"}
The following conditions are equivalent: 

1. 
:::


### Non-measurable set {-}

Write $x\sim y$ if $x-y$ is rational and let $\mca E_\alpha$ 
be the equivalence class of $\alpha$. Then 
$[0, 1]=\bigcup \mca E_\alpha$ and construct 
$\mca N$ by choosing one element $x_\alpha$ from 
each $\mca E_\alpha$. 

:::{.proposition} 
$\mca N$ is not measurable.
:::
_Proof:_ Assume $\mca N$ measurable and let 
$\{r_k\}_{k=1}^\infty$ be an enumeration of all rationals 
in $[-1, 1]$ and consider $\mca N_k = \mca N + r_k$. Then 
all $\{\mca N_k\}$ are disjoint. Note that 
\[ 
    [0, 1] \subset \bigsqcup_{k=1}^\infty \mca N_k \subset [-1, 2]
\] 
Assuming measurability (contradiction!), we have 
\[ 
    1\leq \sum_{k=1}^\infty \mu(\mca N_k) \leq 3 
\] 
Every term in the sum is equal, but there is no real number 
which satisfies the construction above; contradiction: 
there cannot be a disjoint-additive function on the disjoint 
countable collection $\{\mca N_k\}$. 

## Simple functions {-}

:::{.definition name="simple function"}
A simple function is a finite sum 
\[ 
    f = \sum_{k=1}^N a_k \chi_{E_k} 
\] 
where each $E_k$ is a finite-measurable set. 
:::

The following proof is from Ch. 11 of [@rudin1964principles]. 

:::{.theorem #simpleFunctionApproximation name="simple-function approximation"}
Given a real function $f:\Omega\to \R$, there exists a sequence 
$\{s_n\}$ of simple functions such that $s_n(x)\to f(x)$ 
point-wise. If $f$ is measurable, then $\{s_n\}$ 
may be chosen to be a sequence of measurable functions. 
If $f\geq 0$, then $\{s_n\}$ may be chosen to be a monotonically 
increasing sequence. 
:::
_Proof:_ Given $f\geq 0$, define $F_n = f^{-1}([n, \infty))$ and 
\[ 
    E_{n, i} = f^{-1} \left(\left[2^{-n}(i-1), 2^{-n}i \right]\right)
\] 
For $n=1, 2, \cdots$ and $i=1, 2, \cdots, n2^n$, choose 
\[ 
    s_n = n\chi_{F_n} + \sum_{i=1}^{n2^n} \df{i-1}{2^n} \chi_{E_{n, i}}
\] 
Note that $E_{n, i}$ is the pre-image of the $i$-th slice of 
nonnegative real blocks of size $2^{-n}$, and the first term assigns 
$\inf f=2^{-n}(i-1)$ on the corresponding intervals. The second 
term just assigns approximates with $n$ all places where $f(x)\geq n$. 
The second term is reserved for cases where $f(x)=\infty$. In short: 

1. In the $n$-th approximation, approximate $f$ up to value $n$. 
2. Divide $f^{-1}([0, n])$ into $2^{-n}$ pieces and assign a dominated 
    simple function. Approximate the rest simply with $n$. 

If $f$ is measurable, the domains of the characteristic decomposition 
are measurable so $s_n$ is measurable. The general case follows by 
$f=f^+-f^-$. 

## Littlewood's three principles {-}

Littlewood's three principles are: 

1. Every finite-measurable set is almost a finite union of intervals. 
2. Every measurable function is almost continuous. 
3. Every pointwise convergent sequence of measurable functions 
    is almost uniformly convergent. 

To be precise, the third principle is formulated as follows: 

:::{.theorem name="Egorov's theorem"}
Given a a measurable sequence $(f_k)$ on a finite-measurable set 
$E$ with $\mu(E)<\infty$ such that $f_k\to f$ a.e. on $E$. 
For every $\epsilon>0$, there exists a closed set $A_\epsilon \subset E$ 
such that $\mu(E-A_\epsilon)<\epsilon$ and $f_k\to f$ uniformly 
on $A_\epsilon$ 
:::
_Proof:_ without loss of generality assume $f_k\to f$ pointwise (not just 
pointwise a.e.) since we only require $\mu(E-A_\epsilon)<\epsilon$; 
for each $n, k$, define 
\[ 
    E_k^n = \{x\in E: |f_{\forall j>k}(x) - f(x)|<1/n\}
\] 
In other words, this is the set on which $f_{j>k}$ is 
$1/n$-close to $f$ on $E$. Fix $n$. Note that 
$E^n_k\nearrow E$ by $f_k\to f$ (recall definition 
\@ref(def:setSequenceNotation)); then there exists $k_n$ 
such that 
\[ 
    \mu(E - E^n_{k_n}) < 2^{-n}, \quad 
    \sup_{x\in E^n_{k_n}} |f_j(x) - f(x)| < 1/n 
\] 
Choose $N$ so that $\sum_{n=N}^\infty 2^{-n}<\epsilon/2$ and let 
\[ 
    \tilde A_\epsilon = \bigcap_{n\geq N} E^n_{k_n}
\] 
This is domain subset on which, for each $n\geq N$, 
$|f_{j\geq k_n}(x) - f(x)| \leq 1/N$; also note that 
\[ 
    \mu(E - \tilde A_\epsilon) \leq \sum_{n=N}^\infty \mu(E - E^n_{k_n}) 
    < \epsilon/2 
\] 
Also note that $\tilde A_\epsilon$ is measurable since it is the 
intersection of $E^n_k$ which are pre-images; then by measurability 
characterization \@ref(thm:measurableCharacterization) there exists a 
closed $\epsilon/4$-coveree $A_\epsilon$ of $\tilde A_\epsilon$. 
Moreover, $f_k\to f$ uniformly on $A_\epsilon$ since for every 
$0<\epsilon'<1/n$, $|f_j(x)-f(x)|<\epsilon'$ when $j>k_n$ and 
$x\in E^n_{k_n} \supset A_\epsilon$. 

Similarly, the precise statement of the second principle is: 

:::{.theorem name="Lusin's theorem"}
Given measurable $f$ finite-valued on $E$ and $\mu(E)<\infty$, then 
for every $\epsilon>0$ there exists a closed $\epsilon$-coveree 
$F_\epsilon \subset E$ with $\mu(E-F_\epsilon)<\epsilon$ such that 
$f_{|F_\epsilon}$ is continuous in the subspace topology. 
:::
_Proof:_ <span style="color:red"> TODO </span>

<span style="color:green">
Lusin's theorem _does not claim_ that $f$ is continuous on $F_\epsilon$, 
only that $f_{|F_\epsilon}$ is continuous in the subspace topology. 
</span>