# Integration on $\R^n$ {#realIntegration}

This section explores measurable functions and Lebesgue 
integration on $\R^n$. 
 
1. [Measurable functions](#functionMeasurabilityConditions) on $\R^n$: 
    approximation by simple functions, conditions for measurability, 
    limit of measurable functions. 
    - Axler, chapter 3. 
2. [Littlewood's three principles](#littlewoodPrinciples): 
    Egorov's and Luzin's theorems. 
    - Axler, chapter 3. 
3. [Lebesgue integration](#lebesgueConvergence): properties of 
    of the Lebesgue integral, $L^1$ norm. 
    - Rudin, chapter 11. 
4. [Convergence theorems](#lebesgueConvergence): 
    monotone and dominated convergence theorems, 
    Fatou's lemma, relation to Riemann integral. 
    - Rudin, chapter 11. 

Key takeaways: 

1. Limit theorems:
    - Every real measurable function is the pointwise limit of measurable 
        simple functions \@ref(thm:simpleFunctionApproximation). 
    - Pointwise limit of measurable functions is measurable 
        \@ref(prp:limitPreservation). 
2. Littlewood's three principles: 
    - Every measurable set on $\R$ can be approximated up to 
        arbitrary but finite tolerance by a finite union of open intervals. 
    - Egorov's theorem \@ref(thm:egorov):
        for every finite (but arbitrary) tolerance to approximating 
        a domain with finite measure, pointwise convergence a.e. 
        is uniform convergence. 
    - Luzin's theorem \@ref(thm:luzin):
        every $\R\to \R$ measurable function is continuous 
        in the subspace topology of a finite but arbitrary closed approximation 
        to $\R$. 
3. Convergence theorems:
    - Monotone convergence theorem: pointwise monotone limit 
        of nonnegative measurable functions can be exchanged with integration. 
    - Fatou's lemma: $\lim$ of integral $\leq$ integral of $\liminf$ 
    for nonnegative measurable sequences. 
    - Dominated convergence theorem: pointwise dominated limit can be 
        exchanged with integration. 
4. <span style="color:green">
    General technique: prove for characteristic functions, then generalize 
    using approximation and limit theorems. 
    </span>
5. Fatou's lemma can be used to2. Sufficient conditions for measurability: 
    semicontinuous, monotonic, the pointwise limit of a 
    measurable sequence, or equals a measurable function a.e.
3. Properties of the Lebesgue integral:
    - $f$ integrable iff $|f|$ integrable. 
    - disjoint additivity w.r.t. domain. 
    - linear and order-preserving. 
    - sets of measure zero are negligible. 


## Measurable functions on $\R^n$ {#functionMeasurabilityConditions -}

### Simple functions {-}

:::{.definition name="characteristic function"}
Given $E\subset \Omega$, the characteristic function $\chi_E:\Omega\to \R$ is 
\[ 
    \chi_E(x) = \begin{cases}
        1 & x\in E \\ 
        0 & x\notin E
    \end{cases}
\] 
:::

:::{.proposition}
Given $(\Omega, \Sigma), E\subset \Omega$, then 
$\chi_E$ is $\Sigma$-measurable iff $E\in \Sigma$. 
:::
_Proof:_ 
$\chi_E^{-1}(B) = \{E, \Omega-E, \Omega, \emptyset\}$ 
depending on how $B\subset \R$ intersects with $\{0, 1\}$. 

:::{.definition name="simple function"}
A simple function is a finite sum below, 
where each $E_k$ is a finite-measurable set. 
\[ 
    f = \sum_{k=1}^N a_k \chi_{E_k} 
\] 
:::

:::{.theorem #simpleFunctionApproximation name="simple-function approximation"}
Given a real function $f:\Omega\to \R$, there exists a sequence 
$\{s_n\}$ of simple functions such that $s_n(x)\to f(x)$ 
point-wise. If $f$ is measurable, then $\{s_n\}$ 
may be chosen to be a sequence of measurable functions. 
If $f\geq 0$, then $\{s_n\}$ may be chosen to be a monotonically 
increasing sequence. 
:::
<span style="color:green">
Proof idea: in the $n$-th approximation, 
approximate $f\geq 0$ (general case follows by $f=f^+-f^-$) 
up to value $n$ by 
(1) divide $f^{-1}([0, n])$ into $2^{n}$ pieces, 
(2) assign a dominated to each of $2^n$ intervals, and 
(3) approximate $f(x)>n$ with $n$. 
</span>
<details>
<summary>Proof</summary>
Given $f\geq 0$, define $F_n = f^{-1}([n, \infty))$ and 
\[ 
    E_{n, i} = f^{-1} \left(\left[2^{-n}(i-1), 2^{-n}i \right]\right)
\] 
For $n=1, 2, \cdots$ and $i=1, 2, \cdots, n2^n$, choose 
\[ 
    s_n = n\chi_{F_n} + \sum_{i=1}^{n2^n} \df{i-1}{2^n} \chi_{E_{n, i}}
\] 
Note that $E_{n, i}$ is the pre-image of the $i$-th slice of 
nonnegative real blocks of size $2^{-n}$, and the first term assigns 
$\inf f=2^{-n}(i-1)$ on the corresponding intervals. The second 
term just assigns approximates with $n$ all places where $f(x)\geq n$. 
The second term is reserved for cases where $f(x)=\infty$.
If $f$ is measurable, the domains of the characteristic decomposition 
are measurable so $s_n$ is measurable. The general case follows by 
$f=f^+-f^-$. 
</detail>

### Conditions for measurability {-}

:::{.example}
If $\Sigma=\{\emptyset, \Omega\}$, then the only $\Sigma$-measurable 
functions from $\Omega\to \R^n$ are constant functions. On the 
other extreme, if $\Sigma=2^\Omega$, then every function is measurable. 
For a nontrivial example, if $\Sigma=\{\emptyset, (-\infty, 0), [0, \infty), \R\}$ 
then $f:\R\to \R$ is measurable iff it is 
constant on $(-\infty, 0), [0, \infty)$. 
:::

:::{.proposition name="semi-continuity implies measurability"}
Every (lower or upper) semi-continuous $R^n$-valued function 
(definition \@ref(def:semiContinuity)) is measurable. 
:::
_Proof:_ Recall proposition \@ref(prp:measurableFunctionCondition). 
The Borel $\sigma$-algebra is generated by 
half-rectangles $(\infty, t\in \R^n)$ or $(t, \infty)$

The explicit proof below demonstrates the relation between 
continuity and measurability. 

:::{.proposition name="continuity implies Borel measurability"}
Every continuous function $f:\Omega\to \R^n$ defined on 
a Borel subset $\Omega\subset \R^m$ is a Borel-measurable function. 
:::
<details>
<summary>Proof</summary>
Consider the preimage of $x>a$ ($x, a\in \R^n$ and inequality 
holds elementwise). For any such $a$, consider 
\[ 
    f^{-1}(x>a) 
    = \left[\bigcup_{x\in f^{-1}(x>a)} (x-\delta_x, x+\delta_x) \right]\cap \Omega
\] 
Given every $x\in \R^m: f(x)>a$, by continuity $\exists \delta_x\in \R$ 
such that $f((x-\delta_x, x+\delta_x))>a$. The term in the paranthesis 
is an open set, hence its intersection with the Borel set $\Omega$ is Borel. 
</details>

$f:(\Omega\subset \R)\to \R$ is increasing if $x < y\implies f(x)\leq f(y)$; 
it is monotonic if $f$ or $-f$ is increasing. 

:::{.proposition}
if $f:\Omega\to \R$ is monotonic and $\Omega$ is Borel, then $f$ is measurable. 
:::
<details>
<summary>Proof</summary>
Fix $a\in \R$, then for $b=\inf f^{-1}((a, \infty))$, 
monotonicity implies 
\[ 
    f^{-1}((a, \infty)) = (b, \infty)\cap \Omega 
    \text{ or }
    [b, \infty)\cap \Omega
\] 
</details>

:::{.proposition #limitPreservation name="preservation of measurability under limits"}
Suppose a measurable sequence 
$\{f_j\}\to f:(\Omega, \Sigma)\to \R^n$ pointwise 
is $\Sigma$-measurable, then $f$ is $\Sigma$-measurable. 
:::
<details>
<summary>Proof</summary>
Unrolling the definition of the limit: for any 
$x\in \Omega, a\in \R^n$, $f(x)>a$ iff 
\begin{align}
    & \lim_{k\to \infty} f_k(x) > a \\ 
    \iff & \exists j>0, \exists N: f_{\forall k>N}(x)>a+1/j \\ 
    \iff & x\in \bigcup_{j=1}^\infty 
        \bigcup_{N=1}^\infty 
        \bigcap_{k=1}^\infty f_k^{-1}(y>a+1/j)
\end{align}
Note that we only need some $j$ to exist. Each $\exists$ translates 
to $\bigcup$, and each $\forall$ translates to $\bigcap$. Then 
the preimage of $y>a$ the measurable set above. 
</details>

:::{.definition name="extended Borel"}
$A\subset [-\infty \infty]$ is a Borel set if $A\cap \R$ is Borel. 
Extended measurability is defined similarly. 
:::

:::{.theorem name="variational limits are measurable"}
Given measurable $\{f_k: (\Omega, \Sigma)\to \R\}$, the following functions 
are also measurable: 
\[ 
    g(x) = \inf_k f_k(x), \quad h(x) = \sup_k f_k(x)
\] 
:::
<details>
<summary>Proof</summary>
It suffices to verify for the $\sup$ case that 
\begin{align}
    h(x) > a &\implies \exists k: f_k(x) > a \\ 
    h^{-1}((a, \infty]) &= \bigcup_{k=1}^\infty f_k^{-1}((a, \infty])
\end{align} 
</details>

:::{.proposition name="a.e. measurability"}
Given $f$ measurable and $f=g$ a.e. (they differ on a set of 
measure $0$ on the domain), then $g$ is measurable. 
:::
<details>
<summary>Proof</summary>
The symmetric difference of the 
pre-images $f^{-1}, g^{-1}$ is dominated by a set of 
measure $0$, then by $f$-measurability $g^{-1}(A)$ 
is measurable for $A$ measurable 
(proposition \@ref(prp:nullDifferenceMeasurability)). 
</details>

## Littlewood's three principles {#littlewoodPrinciples -}

Littlewood's three principles (at least the ones we prove) 
apply to $\R$ and real-valued functions on the real domain.  

1. Every finite-measurable set is almost a finite union of intervals. 
2. Every measurable function is almost continuous. 
3. Every pointwise convergent sequence of measurable functions 
    is almost uniformly convergent. 

It is convenient to first introduce some notation for monotone limits. 

:::{.definition #setSequenceNotation name="sequence of sets"}
An increasing sequence of sets $\{A_n\}$ is a sequence 
\[ 
    A_1\subset A_2\subset \cdots \to A = \bigcup_{n=1}^\infty A_n
\] 
also written $A_j\nearrow A$. Similarly, a decreasing 
sequence of sets is written $A_j\searrow A$. 
\[ 
    A_1\supset A_2\supset \cdots \to A = \bigcap_{n=1}^\infty A_n 
\] 
:::

:::{.proposition name="Littlewood's first principle"}
Given measurable $E\subset \R$ with $\mu(E)<\infty$, 
there exists a finite union $O$ of intervals such that 
$\mu(O\Delta E) < \epsilon$ for every $\epsilon$. 
:::
<span style="color:green">
Proof idea: prove for open $E$ and apply theorem 
\@ref(thm:squeezeMeasurable). 
</span>
<details>
<summary>Proof</summary>
Every open set $O$ is the interval of countably many disjoint 
open intervals (this is because every disjoint interval contains 
a rational number, of which there are countably many), then 
$\mu(O) = \sum_{j=1}^n \mu((a_j, b_j))$. Thus for every $\epsilon>0$ 
we can choose a $\epsilon$-approximation with finite intervals. 
Apply theorem \@ref(thm:squeezeMeasurable) to obtain the result 
for general measurable sets. 
</details>

To be precise, the third principle is formulated as follows: 

:::{.theorem #egorov name="Egorov's theorem"}
Consider a measurable sequence $f_k\to f$ a.e. on a finite-measurable set 
$E$ with $\mu(E)<\infty$. For every $\epsilon>0$, 
there exists a closed set $A_\epsilon \subset E$ such that $f_k\to f$
uniformly and $\mu(E-A_\epsilon)<\epsilon$ 
on $A_\epsilon$. 
:::

<span style="color:green">
Proof idea: given domain tolerance $\epsilon$, construct by pointwise convergence 
a family $F_n$ of $(\epsilon 2^{-n})$-domain approximations 
on which $f_j$ will  uniformly $1/n$-approximate $f$ on $F_n$. 
Then $f_j\to f$ uniformly on the intersection $A_\epsilon$ of $F_n$, 
which is also an $\epsilon$-domain approximation. 
</span> 
<details>
<summary>Proof</summary>
Note that we can't simply use compactness here since the domain approximation 
may be unbounded. 

1. Translate pointwise convergence: fixing $n\in \N$, for every 
    $x\in X$ there exists $m\in \N$ such that $f_{\forall k\geq m}$ 
    will $\epsilon$-approximate $f$ at $x$, then 
    \[ 
        X = \bigcup_{m=1}^\infty A_{m, n}, \quad 
        A_{m, n} = \bigcap_{k=m}^\infty 
        \{x: |f_k(x) - f(x)| < 1/n\}
    \] 
    Here $A_{m, n}$ is the domain on which $f_{\forall k\geq m}$ 
    will $1/n$-approximate $f$. 
2. Given domain tolerance $\epsilon>0$, for each $n>0$ 
    we can find $m_n$ such that 
    \[ 
        \mu(X) - \mu(A_{m_n, n}) < \df \epsilon {2^n}
    \] 
    This definition implies that $f_{\forall j\geq m_n}$ 
    will $1/n$-approximate $f$ on $A_{m_n, n}$. 
3. Let $A_\epsilon = \bigcap_{n=1}^\infty A_{m_n, n}$; 
    then for every $\epsilon'>1/N>0$, $f$ will be 
    $\epsilon'$-approximated by $f_{j\geq m_N}$ on 
    $A_\epsilon \subset A_{M_N, N} \subset A_\epsilon$. 
4. Argue for $\epsilon$-approximation of the domain: 
\begin{align}
    \mu(\Omega - A_\epsilon) 
    &= \mu \bigcup_{n=1}^\infty \Omega - A_{m_n, n} 
    \leq \sum_{n=1}^\infty \epsilon/2^n < \epsilon
\end{align}
5. We can choose $A_\epsilon$ to be closed by the characterization 
    of measurable sets (theorem \@ref(thm:squeezeMeasurable)). 
</details>

Similarly, the precise statement of the second principle is as follows. 
Note that _does not claim_ that $f$ is pointwise continuous on $F_\epsilon$ 
in the topology of $\R$, only that $f_{|F_\epsilon}$ 
is continuous in the subspace topology. 

:::{.lemma #luzinLemma}
Given a Borel-measurable $f:\R\to \R$, for every $\epsilon>0$ 
there exists a closed $F\subset \R$ with $|\R - F|<\epsilon$ 
such that $f_{|F}$ is continuous on $F$. 
:::
<span style="color:green">
Proof idea: establish for (1) simple functions, 
(2) arbitrary functions on compact interval, using pointwise approximation 
by simple functions and Egorov's theorem, and (3) extended domain by 
pasting local chunks. 
a.e.
</span>
<details>
<summary>Proof</summary>
First assume $f = \sum_{j=1}^N \alpha_j \chi_{E_j}$. 
By theorem \@ref(thm:squeezeMeasurable) choose $U_j\supset E_j\supset F_j$ 
with $U_j$ open, $F_j$ closed, and both are $(\epsilon/2n)$-approximations 
of $E_j$. 
The closed set is the union of each $F_j$ and $U_j^c$: 
\[ 
    E = F \cup (\R - U), \quad F = \bigcup_{j=1}^N F_j, \quad 
    U = \bigcup_{j=1}^N U_j 
\] 
both $F, U^c$ are closed and $\mu(\R-E) < \epsilon$. Continuity on $E$ 
follows by $f$ being constantly zero on disjoint closed intervals, 
so the pasting lemma applies. 

Next consider general $f$ on a compact interval. 
Every $f$ is the pointwise limit of simple functions
(theorem \@ref(thm:simpleFunctionApproximation)) and 
their uniform limit on a closed subset (Egorov's theorem \@ref(thm:egorov)) 
thus continuous. 

To extend the domain, construct $\epsilon\cdot 2^{-n-1}$-approximations 
to $f$ on $[-n, 1-n]$ and $[n-1, n]$ and apply the pasting lemma. 
</details>

:::{.theorem #luzin name="Luzin's theorem"}
Given a Borel measurable $f:(E\subset \R)\to \R$, for every $\epsilon>0$ 
there exists a closed $\epsilon$-approximation 
$F \subset E$ such that $f_{|F}$ is continuous in the subspace topology. 
:::
_Proof:_ Apply lemma \@ref(lem:luzinLemma) 
    to the continuous extension of $f$ to all of $\R$. 

## Lebesgue integration {#lebesgueIntegration -}

:::{.definition name="function support"}
The support of a measurable function $f$ is 
\[ 
    \supp(f) = \overline{f^{-1}(\{0\}^C)}
\] 
the closure of domain on which $f$ does not vanish. 
:::

:::{.definition name="S-partition"}
Given a $\sigma$-algebra $\Sigma$ on $\Omega$, a
$S$-partition of $\Omega$ is a _finite_ collection 
$A_1, \cdots, A_m\in \Sigma$ of disjoint sets 
such that $\bigsqcup A_j = \Omega$. 
:::

:::{.definition name="lower Lebesgue sum"}
Given measure space $(\Omega, \Sigma, \mu)$, 
an $\Sigma$-measurable function $f:\Omega\to [0, \infty]$, 
and a $\Sigma$-partition $P=\{A_1, \cdots, A_m\}$ of $\Omega$, 
the lower Lebesgue sum is 
\[ 
    \mca L_\mu(f, P) = \sum_{j=1}^m \mu(A_j)\inf_{A_j} f 
\] 
:::

:::{.definition #nonNegativeIntegral name="nonnegative integral"}
The integral of a non-negative function $f:\Omega\to [0, \infty]$ 
w.r.t. the measure $(\Sigma, \mu)$ is the following $\sup$ with 
$P$ over all S-partitions of $\Omega$: 
\[ 
    \int f\, d\mu = \sup_P \mca L_\mu(f, P)
\] 
:::

:::{.proposition name="base case for Lebesgue integral"}
Given $(\Omega, \Sigma, \mu)$ and measurable $E\in \Sigma$, 
we have $\int \chi_E\, d\mu = \mu(E)$. 
:::
<details>
<summary>Proof</summary>
We have $\mca L_\mu(\chi_E, \{E, \Omega-E\}) = \mu(E)$, then 
$\int f\, d\mu \geq \mu(E)$. Conversely, given any S-partition 
$P=\{A_1, \cdots, A_m\}$ of $\Omega$, for each $j$ 
\[ 
    \mu(A_j) \inf_{A_j} \chi_E = \begin{cases}
        \mu(A_j) & A_j\subset E \\ 
        0 & \text{otherwise}
    \end{cases}
\] 
then $\mca L(\chi_E, P) = \sum_{A_j\subset E} \mu(A_j) \leq \mu(E)$. 
</details>

:::{.proposition name="integral of a simple function"}
Given a measure space $(\Omega, \Sigma, \mu)$ and disjoint
$E_1, \cdots E_n$, we have 
\[ 
    \int \left(\sum_{k=1}^n c_k \chi_{E_k}\right)\, d\mu 
    = \sum_{k=1}^n c_k \mu(E_k)
\] 
:::
<details>
<summary>Proof</summary>
The LHS integral is lower-bounded by the $\Sigma$-partition 
$\{E_j\}\cup \{\Omega-\bigcup E_j\}$. The converse follows similar 
to the last proposition. 
</details>

:::{.corollary name="equivalent definition of nonnegative integral"}
Given $(\Omega, \Sigma, \mu)$ and measurable $f:\Omega\to [0, \infty]$, 
the integral definition \@ref(def:nonNegativeIntegral) is equivalent to 
\[ 
    \int f\, d\mu = \sup_P \mca L_\mu(f, P) = \sup_{s\leq f} \int s\, d\mu 
\] 
where the last $\sup$ is taken over all simple function $f$ dominated 
by $f$: $\forall x\in \Omega: f(x)\geq s(x)$. 
:::
_Proof:_ Follows from $\mca L_\mu(f, P)$ being 
the integral of a simple function. 

:::{.definition name="Lebesgue integral"}
Given $(\Omega, \Sigma, \mu)$ and measurable 
$f(x)\in [-\infty, \infty]$ with $f=f^+-f^-$ and $f^+, f^-\geq 0$. 
If _at least one_ of $\int f^+\, d\mu, \int f^-\, d\mu$ 
is finite, then the Lebesgue integral of $f$ is 
\[ 
    \int f\, d\mu = \int f^+\, d\mu - \int f^-\, d\mu 
\] 
:::

Note that, for example, the integral of the following function is not defined: 
\[ 
    f(x) = \begin{cases}
        1 & x\geq 0 \\ -1 & x < 0
    \end{cases}
\] 

:::{.definition name="integral metric, integrable space"}
Fix $(\Omega, \Sigma, \mu)$; if $f:\Omega\to [-\infty, \infty]$ 
is measurable, then the $L^1$-norm of $f$ is 
\[  
    \|f_1\| = \int |f|\, d\mu 
\] 
The Lebesgue space $L^1(\mu)$ is also 
defined as 
$L^1(\mu) = \{f:\Omega\to \R \text{ satisfying } \|f\|_1 < \infty \}$. 
:::

:::{.theorem name="properties of integration"}
The following properties are evident for $f, g\in L^1(\mu)$: 

1. _Linearity:_ $\int cf+g\, d\mu = c\int f\, d\mu + \int g\, d\mu$. 
2. _Order-preserving_: $f\leq g\implies \int f\, d\mu \leq \int g\, d\mu$. 
3. $\left|\int f\, d\mu\right| \leq \int |f|\, d\mu$. 
:::
<details>
<summary>Proof</summary>
General idea is to establish for simple functions, then 
show that the proof commutes with integral construction. 
For (2), use $\int g\, d\mu - \int f\, d\mu = \int (g-f)\, d\mu$. 
For (3), 
\begin{align}
    \left|\int f\, d\mu\right| 
    &= \left| \int f^+\, d\mu - \int f^-\, d\mu\right| 
    \leq \int f^+\, d\mu + \int f^-\, d\mu \\ 
    &= \int (f^++f^-)\, d\mu 
    = \int |f|\, d\mu 
\end{align}
</details>

:::{.definition name="integration on subset"}
Given $(\Omega, \Sigma, \mu)$ and $E\in \Sigma$ and 
measurable $f:\Omega\to [-\infty, \infty]$, the subset integral is 
\[ 
    \int_E f\, d\mu = \int \chi_E f\, d\mu 
\] 
:::

:::{.proposition #integralBound name="integral bound"}
Given $\int_E f\, d\mu < \infty$, 
\[ 
    \left|\int_E f\, d\mu \right| \leq \mu(E) \sup_E |f|
\] 
:::
<details>
<summary>Proof</summary>
Let $c=\sup_E |f|$, then 
$\displaystyle \left|\int_E f\, d\mu\right| \leq \int \chi_E |f|\, d\mu 
    \leq \int c\chi_E \, d\mu = c\mu(E)$. 
</details>

:::{.theorem #domainIntegralAdditivity name="disjoint additivity w.r.t domain"}
Given measurable $f$, define the function 
$\phi:\Sigma\to [-\infty, \infty]$ by 
\[ 
    \phi(A) = \int_A f\, d\mu 
\] 
then for every $A, B\in \Sigma$, we have 
$\phi(A\sqcup B) = \phi(A)+\phi(B)$. 
:::
<details>
<summary>Proof</summary>
Without loss of generality consider nonnegative $f$. 
If $f$ is a characteristic function, then countable additivity 
is equivalent to the countable subadditivity of $\mu$. 
The general proof just demonstrates the commutativity of 
countable subadditivity with the $\sup$ integral construction. 
</details>

:::{.corollary name="sets of zero measure are negligible in integration"}
Given 
$A, B\in \Sigma$ such that $\mu(A-B)=0$, then 
\[ 
    \int_A f\, d\mu = \int_B f\, d\mu 
\] 
:::
<details>
<summary>Proof</summary>
Follows from additivity theorem 
\@ref(thm:domainIntegralAdditivity) and applying $\mu(A-B)=0$ 
to proposition \@ref(prp:integralBound). 
</details>

The integrability of $f$ implies that of $|f|$, and the 
Lebesgue integral is often called an absolutely convergent integral. 

:::{.proposition name="several conditions for integrability"}

1. $f\in L^1(\mu)\implies |f|\in L^1(\mu)$. 
2. $f$ is measur_Proof:_able and $|f|\leq g \in L^1(\mu)\implies f\in L^1(\mu)$. 
:::
_Proof:_ for (1), recall that $f\in L^1(\mu)$ if both $f^+, f^-$ 
have finite integrals, then $|f|=f^++f^-$ is integrable. 
Similarly, (2) follows from $f^+, f^-\leq g$. 

## Convergence theorems {#lebesgueConvergence -}

The following convergence theorems are the cornerstone of 
Lebesgue theory: 

:::{.theorem #monotoneConvergence name="Lebesgue's monotone convergence theorem"}
Given $E$ measurable, let $\{f_n\}$ be a sequence of 
measurable functions such that $0\leq f_1\leq \cdots$ on $E$
and $f_n\to f$, then 
\[ 
    \lim_{n\to \infty} \int_E f_n \, d\mu 
    = \int_E \lim_{n\to \infty} f_n\, d\mu 
\] 
Pointwise monotone convergence of measurable functions 
on a measurable set implies convergence of integral. 
:::
<span style="color:green">
Proof idea: one direction of the inequality is trivial; 
the other is established by first proving for a 
dominated simple approximations of $f$ then taking the $\sup$. 
</span> 
<details>
<summary>Proof</summary>
In one direction, the implied equation holds for each $m$ thus in limit 
\[ 
    f_n \leq f\implies \lim_{m\to \infty} 
    \int f_m\, d\mu \leq \int_E \lim_{n\to \infty} f_n \, d\mu 
\] 
To establish the other direction, fix 
$c\in (0, 1)$ and a dominated simple approximation $s\leq f$. Define 
\[ 
    E_n = \{x| f_n \geq c s\} 
\] 
Note that $E_j \nearrow E$ 
(recall notation \@ref(def:setSequenceNotation)). 
For every $n$ 
\[  
    \int_E f_n \, d\mu \geq \int_{E_n} f_n\, d\mu 
    \geq c\int_{E_n} s\, d\mu 
\] 
Let $n\to \infty$ and take the limit $c\to 1$ to obtain 
\[ 
    \int \lim_{n\to \infty} f_n\, d\mu \geq 
    \lim_{n\to \infty} \int_{E_n} f_n \, d\mu 
    \geq c\int_E s\, d\mu 
\] 
Take the $\sup$ over all $s$ and the simple function approximation 
theorem \@ref(thm:simpleFunctionApproximation) to obtain 
$F\geq \int_E f\, d\mu$. 
</details> 

Applying the monotone convergence theorem above to 
partial sums yield 

:::{.corollary}
Given measurable $E\in \Sigma$ and nonnegative measurable sequence 
$(f_j)$; define their sum 
\[ 
    f = \sum_{n=1}^\infty f_n 
\] 
then $\int_E f = \sum_{n=1}^\infty \int_E f_n\, d\mu$. 
:::

:::{.lemma #fatou name="Fatou's lemma"}
For measurable $E$, given nonnegative measurable 
sequence $(f_j)$ and 
\[ 
    f(x) = \liminf_{n\to \infty} f_n(x) 
\] 
then the integral is similarly bounded 
\[ 
    \int_E f\, d\mu \leq \liminf_{n\to \infty} \int_E f_n\, d\mu 
\] 
:::
<span style="color:green">
Apply the dominated convergence theorem (carefully! expand to see details) 
to $g_j = \inf_{k\geq j} f_j$. 
</span> 
<details>
<summary>Proof</summary>
Define $g_n = \inf_{i\geq n} f_i$, then $g_n$ is 
measurable and 
\[ 
    i\leq j\implies g_i\leq g_j, \quad g_n\to f 
\] 
Applying the monotone convergence theorem yields 
\[ 
    \int_E g_n\, d\mu \to \int_E f\, d\mu 
\] 
<span style="color:green">
Note that this _does not_ imply equality because the 
monotone convergence theorem above yields the first equality, 
and the second inequality may be strict 
\[ 
    \int_E f\, d\mu 
    = \lim_{n\to \infty} \int_E \inf_{k\geq n} f_k\, d\mu 
    \leq \int_E f\, d\mu 
    = \lim_{n\to \infty} \inf_{k\geq n} \int_E f_k\, d\mu 
\] 
There exist examples (see below) where 
measure is lost through $\inf f_k$ 
but not through the $\inf$ of the integral. 
</span>
</details>

:::{.example name="strict inequality in Fatou's theorem"}
Let $g(x) = (0\leq x\leq 1/2)^?0:1$ and 
\[ 
    f_{2k}(x) = g(x), \quad f_{2k+1} = g(1-x)
\] 
then $\liminf_{n\to \infty} f_n = 0$ but 
$\forall n, \int_0^1 f_n(x)\, dx = 1/2$. 
:::

:::{.theorem #dominatedConvergence name="Lebesgue's dominated convergence theorem"}
Given measurable sequence $(f_j)\to f$ pointwise and 
$|f_j| \leq g$ with $g$ measurable, then 
\[ 
    \lim_{n\to \infty} \int_E f_n\, d\mu = \int_E f\, d\mu 
\] 
As a corollary, $L^1$ is complete under dominated 
pointwise convergence. 
:::
<span style="color:green">
Apply Fatou's theorem to $f_n+g\geq 0$ and $g-f_n\geq 0$. 
</span> 
<details>
<summary>Proof</summary>
First note that $f_j, f$ are integrable since 
they're dominated by $g$. By $f_n+g\geq 0$, 
invoke Fatou's theorem 
\[ 
    \int_E (f + g)\, d\mu \leq 
    \liminf_{n\to \infty} \int_E (f_n+g)\, d\mu 
    \implies \int_E f\, d\mu \leq \liminf_{n\to \infty} \int_E f_n\, d\mu 
\] 
and pull $g$ out of both sides. Again, by $g-f_n\geq 0$ see 
\begin{align}
    \int_E (g - f)\, d\mu &\leq 
    \liminf_{n\to \infty} \int_E (g - f_n)\, d\mu \\ 
    -\int_E f\, d\mu &\leq 
    \liminf_{n\to \infty} \int_E -f_n\, d\mu 
    =-\limsup_{n\to \infty} \int_E f_n\, d\mu 
\end{align}
Combine the two results to obtain equality 
\[ 
    \limsup_{n\to \infty} \int_E f_n\, d\mu 
    \leq \int_E f\, d\mu \leq 
    \liminf_{n\to \infty} \int_E f_n\, d\mu 
\] 
</details>

:::{.corollary name="bounded convergence theorem"}
Given finite-measurable $\mu(E) < \infty$ and uniformly bounded 
convergent sequence $(f_n)\to f$ (i.e. $|f_n(x)|\leq M$ for all $n, x$), 
the dominated convergence theorem applies. 
:::
_Proof:_ Given finite measure $\mu(E)<\infty$, the 
constant-$M$ function is integrable and dominates $(f_n)$. 


### Comparison with Riemann integral {-}

Denote the Riemann integral by $\mca R\int_a^b f\, dx$. 

:::{.theorem name="compatibility with Riemann integral"}
A function $f$ Riemann integrable on $[a, b]$ 
implies $f\in L^1([a, b])$ and 
\[ 
    \int_a^b f\, dx = \mca R \int_a^b f\, dx 
\] 
:::
By existence of the Riemann integral, there 
exists a countable sequence of iteratively refined partitions $P_k$ 
such that 
\[ 
    \lim_{k\to \infty} L(P_k, f) = \mca R \underline{\int} f\, dx, \quad 
    \lim_{k\to \infty} U(P_k, f) = \mca R \bar \int f\, dx 
\] 
For each partition $P_k$, define functions $U_k(x\in [x_{j-1}, x_j])$ and 
$L_k$ to be the sup and inf along the interval, respectively, then 
in the Lebesgue sense, 
\[ 
    L(P_k, f) = \int L_k\, dx, \quad U(P_k, f) = \int U_k\, dx 
\] 
the functions are also monotone 
$L_1 \leq L_2 \leq \cdots \leq f \leq \cdots \leq U_1$. 
Let $L_k\to L, U_k\to U$, then $L, U$ are bounded measurable functions 
with $L\leq f\leq U$. Then 
\[ 
    \int L\, dx = \mca R \underline \int f\, dx, \quad 
    \int U\, dx = \mca R \bar \int f\, dx 
\] 
by the monotone convergence theorem. Further note that $f$ is 
Riemann-integrable iff $\int L\, dx = \int U\, dx$. 
This implies $L=U$ a.e. since $L\leq U$, then $L=f=U$ a.e. and $f$ 
is measurable; equality with Lebesgue integral follows. 


:::{.theorem name="Riemann integrability theorem"}
Given $f$ bounded on $[a, b]$, then the Riemann integral $\mca R\int_a^b f\, dx$ 
exists iff $f$ is continuous a.e. on $[a, b]$. 
:::
_Proof:_ Extending the last proof: 
for any $x\notin P_k$ for any $k$, we have $U(x)=L(x)$ iff $f$ 
is continuous at $x$ (think about this! equivalent to saying that 
$\sup\approx \inf$ arbitrarily close intervals about $x$); the union 
$\bigcup P_k$ is countable of measure $0$, then $f$ is continuous a.e. 
iff $L=U$ a.e. iff $f$ is Riemann-integrable on $[a, b]$. 