# Iterated integrals {#iteratedIntegrals}
Key takeaways: 

1. The product $\sigma$-algebra is characterized by the 
    section property (proposition \@ref(prp:productSection)). 
2. $\sigma$-finiteness is extremely important. 

## Properties of products {-}

Recall that the product $\sigma$-algebra 
$\Sigma_1\times \Sigma_2$ is freely generated by 
measurable rectangles (definition \@ref(def:productSigmaAlg)). 

:::{.definition name="(cross) sections"}
Given sets $X, Y$ and $E\subset X\times Y$, define 
for $x\in X, y\in Y$ the sections 
\[ 
    [E]_x = \{y\in Y: (x, y)\in E\}, \quad 
    [E]^y = \{x\in X: (x, y)\in E\}
\] 
The notation should be reminiscent of slicing along 
$X=x$ on the horizontal, or $Y=y$ on the vertical axis. 
Similarly, the sections of $f$ defined on $X\times Y$ is 
\[ 
    [f]_x(y) = [f]^y(x) = f(x, y)
\] 
:::

:::{.proposition #measurableSectionSets name="sections of measurable sets are measurable"}
The product $\sigma$-algebra $\Sigma = \Sigma_1\times \Sigma_2$ 
has the section property that, $\forall A\in \Sigma$, 
\[ 
    [A]_{\forall x\in \Omega_1}\in \Sigma_2, \quad 
    [A]^{\forall y\in \Omega_2} \in \Sigma_1 
\] 
:::
<details>
<summary>Proof</summary>
The set $\Sigma'$ of all subsets of $\Omega_1\times \Omega_2$ 
(regarded as Cartesian product of sets) 
satisfying the section property is a $\sigma$-algebra containing 
$\Sigma_1\times \Sigma_2$ (since sections of the Cartesian 
product of measurable sets are measurable); 
the proof concludes by the universal 
property of $\Sigma_1\times \Sigma_2$, which is the smallest 
$\sigma$-algebra generated by products of measurable sets. 
</details>

:::{.proposition #measurableSectionFunctions name="sections of measurable functions are measurable"}
Given a $\Sigma_1\times \Sigma_2$ measurable function 
$f$ on $\Omega_1\times \Omega_2$, then 
$[f]_{\forall x\in \Omega_1}$ is a measurable function 
on $\Omega_2$, and $[f]^{\forall y\in \Omega_2}$ is a measurable 
function on $\Omega_1$. 
:::



:::{.definition name="product measures"}
The product of two measure spaces is 
\[ 
    (\Omega_1\times \Omega_2, \Sigma_1\times \Sigma_2, \mu_1\times \mu_2) 
    = (\Omega_1, \Sigma_1, \mu_1)\times (\Omega_2, \Sigma_2, \mu_2)
\] 
where $\Omega_1\times \Omega_2$ is the Cartesian product of sets, 
$\Sigma_1\times \Sigma_2$ is the $\sigma$-algebra product 
\@ref(def:productSigmaAlg), 
and $\mu_1\times \mu_2$ is uniquely 
defined by the requirement 
\[ 
    \mu(A_1\times A_2) = \mu_1(A_1) \mu_2(A_2)
\] 
The exact definition and uniqueness of the 
product measure is postponed to 
theorem \@ref(thm:productMeasure). 
:::


## Fubini's theorem {-}

:::{.theorem #productMeasure name="product measure"}
Placeholder. 
:::