
# Spaces of functions {#banachSpaces}

Nontrivialities arise when we generalize from finite-dimensional 
to infinite-dimensional vector spaces. 
The theory of normed vector spaces provide the foundation 
of dual spaces, weak topology, and convex theory;  
Banach spaces include $L^p$ spaces of integrable 
functions we will later be working with, so we take time  
to develop some of their properties. This section, 
works with $\mbb F$ which can be either real or complex. 

1. [Normed vector spaces, Hahn-Banach](#vectorSpace): 
    existence of a basis, normed space of linear operators, 
    characterization of continuous linear functionals and operators, 
    graphs, the Hahn-Banach theorem, variational formula of the norm, 
    weak topology and convergence. 
2. [Banach theorems](#banachSpace): 
    Baire's (category) theorem, 
    open mapping theorem, inverse mapping theorem, 
    principle of uniform boundedness, bounded inverse theorem, 
    closed graph theorem. 

Key takeaways: 

1. A basis in infinite-dimensional vector spaces spans by 
    **finite** linear combinations, and the dual space 
    (definition \@ref(def:dualSpace))
    consists of the set of **bounded** or, equivalently, continuous 
    linear functionals under the operator norm
    (definition \@ref(def:operatorNorm)); $\mca B(V, W)$ 
    is Banach if $W$ is Banach \@ref(prp:banachDualInheritance). 
1. The existence of a basis for infinite-dimensional vector space is 
    is nontrivial and nonconstructive (theorem \@ref(thm:vectorBasisExistence)). 
2. Continuity of linear maps cannot be taken for granted in 
    infinite-dimensional vector spaces. A linear map is continuous 
    iff bounded (theorem \@ref(thm:continuousLinear)). 
    Every infinite-dimensional normed vector space has a 
    discontinuous linear functional 
    (proposition \@ref(prp:disctLinearFunctional)). 
3. Universal property of the weak topology \@ref(def:weakTopology). 
3. The Hahn-Banach theorem \@ref(thm:hahnBanach) can be viewed 
    as an existence result of a minimization problem: what is 
    the minimum norm of the extension of a bounded linear functional 
    to the whole space? 
4. Baire's theorem \@ref(thm:baire): 
    every closed cover of a Banach space contains an element which has 
    nonempty interior. 
5. Baire's theorem leads to the principle of 
    uniform boundedness (corollary \@ref(cor:uniformBounded)): 
    every family of pointwise bounded linear operators from a 
    Banach space to a normed vector space is uniformly bounded. 
    Completeness (for continuous / bounded linear maps) 
    plays a role similar to compactness (for continuous maps).  
6. The closed graph theorem \@ref(thm:closedGraph) 
    is nontrivial since demonstrating continuity needs to show that (1) 
    the limit exists, and (2) the limits are equal; but CGT 
    reduces this to checking the closure of the graph. 


## Normed spaces, Hahn-Banach {#vectorSpace -}

:::{.definition name="(Hamel) basis"}
A subset $B\subset V$ of a vector space $V$ is a (Hamel) 
basis if it is linearly independent and every $v\in V$ can 
be written as a <span style="color:green">finite</span> 
linear combination of elements in $V$. 
:::

Zorn's lemma is in fact equivalent to the axiom of choice; 
it is responsible for the nonconstructive existence result 
for the basis of infinite-dimensional vector spaces. 
We will take it for granted. 
Fun quote from Wikipedia: 

> If you are building a mathematical object in stages and 
> find that (i) you have not finished even after infinitely 
> many stages, and (ii) there seems to be nothing to stop you 
> continuing to build, then Zorn’s lemma may well be able to 
> help you. 
> `r tufte::quote_footer('--- William Timothy Gowers')`

:::{.lemma #zorn name="Zorn's lemma"}
Given a partially ordered set $P$ in which every 
chain (subset with pairwise comparable elements) has an upper bound 
in $P$, then $P$ contains at least one maximal element. 
:::

:::{.theorem #vectorBasisExistence name="existence of basis"}
Every infinite-dimensional vector space $V$ has a basis. 
:::
<details>
<summary>Proof</summary>
Consider the space $A\subset 2^V$ of all linearly independent 
subsets of $V$, partially-ordered by set inclusion. 
Every chain $B_1\subset B_2\cdots \in A$ is upper-bounded 
$B_j\nearrow B$ (which is still linearly independent!), 
then the maximal element is precisely a basis, else 
the vector not in the finite linear span could be added to 
extend the basis. 
</details>

:::{.definition #operatorNorm name="(normed) space of (bounded) linear operators"}
Given two vector spaces $U, V$, the set of linear 
operators from $U$ to $V$ is also a vector space, 
which we denote $\mca L(U, V)$. If $U, V$ are normed, 
then $\mca L(U, V)$ is equipped with the **operator norm**
\[ 
    \|T\| = \sup_{\|f\in U\|\leq 1} \|Tf\|
\] 
The set of bounded linear operators is denoted $\mca B(U, V)$. 
:::

:::{.definition name="bounded linear functional"}
A linear functional on a vector space $V$ 
is a linear map of signature $T:V\to \mbb F$. 
It is bounded if $\|T\|<\infty$ using the operator norm. 
:::

:::{.theorem #continuousLinear name="characterization of continuous linear maps"}
A linear map $T:U\to V$ is continuous iff it is bounded. 
:::
<details>
<summary>Proof</summary>
Given $T$ bounded, for every $f_j\to f\in U$, 
we have continuity from 
\[ 
    \|Tf_k - Tf\| \leq \|T\| \, \|f_k - f\|
\]
Conversely, assume $T$ unbounded, then there exists 
a sequence $f_j\in V$ with $\|f_j\|\leq 1$ and $\|T f_{k\to \infty}\| \to \infty$. 
Then 
\[ 
    \lim_{k\to \infty} \df{f_k}{\|T f_k\|} = 0, \quad T\, \df{f_k}{\|T f_k\|} 
    \not \to 0
\]  
</details>

:::{.theorem #continuousLinear name="characterization of continuous linear functionals"}
A linear functional $\varphi:U\to \F$ which is not identally $0$ 
is continuous iff it is bounded iff: 

1. $\ker \varphi$ is a closed subspace of $V$. 
2. $\overline{\ker \varphi} \neq V$. 
:::
<details>
<summary>Proof</summary>
Continuity implies (1) since $\ker \varphi = \varphi^{-1}(\{0\})$ and 
continuous maps send closed singletons to closed sets. Conversely, 
$\varphi$ unbounded implies $\exists f_j\in V$ such that $\|f_j\|\leq 1$ 
and $|\varphi\, f_j|>j$ for each $j$, note that 
\[ 
    \forall j, \quad \df{f_1}{\varphi\, f_1} 
    - \df{f_k}{\varphi\, f_k} \in \ker \varphi
\] 
On the other hand, we have 
\[ 
    \lim_{k\to \infty} \df{f_1}{\varphi\, f_1} 
    - \df{f_k}{\varphi\, f_k} = \df{f_1}{\varphi\, f_1} 
    \notin \ker \varphi 
\] 
thus $\overline{\ker \varphi}\neq \ker \varphi$ if $\varphi$ unbounded. 
Finally prove equivalence with (2), we have (1) implies (2) 
since $V$ is closed. Conversely, if 
$\overline{\ker \varphi} \supsetneq \ker \varphi$, we will show that 
$\overline{\ker \varphi} = V$. To do so, let 
$f\in \overline{\ker \varphi} - \ker \varphi$, then $\forall g\in V$: 
\[ 
    g = \left(g - \df{\varphi\, g}{\varphi\, f} 
    f\right) + \df{\varphi\, g}{\varphi\, f} f
\] 
Recall that $\overline{\ker \varphi}$ is a vector space. 
The term in the big paranthesis is in $\ker \varphi$, and the 
trailing term is in $\overline{\ker \varphi}$, thus
$g\in \overline{\ker \varphi}$ for every $g\in V$. 
</details>

:::{.proposition #disctLinearFunctional}
Every infinite-dimensional normed vector space has a 
    discontinuous linear functional. 
:::
_Proof:_ Consider a basis $\{e_j\in V\}_{j\in \Gamma \supset \mbb N}$. 
The linear functional which maps $e_j$ to $j$ is discontinuous.  

:::{.definition #dualSpace name="dual space"}
Given a normed vector space $V$, its dual space $V^*$ 
consists of the vector space of bounded linear operators 
under the operator norm (definition \@ref(def:operatorNorm)). 
:::

:::{.definition #weakTopology name="weak topology, convergence"}
The weak topology on a normed vector space 
$V$ is the coarsest topology in which all continuous 
linear functionals on the space remain continuous. 
A sequence $f_j$ in a normed vector space $V$ converges 
weakly to $f\in V$ if $\alpha\, x_n\to \alpha\, x$ for all 
$\alpha \in V^*$. 
:::

We next proceed to prove the Hahn-Banach theorem. 

:::{.lemma #extLemma name="extension lemma"}
Given a real normed vector space $V$, 
a subspace $U\subset V$, and a bounded linear functional 
$\psi:U\to \R$. For every $h\in V-U$, there exists 
a linear functional $\varphi:U\oplus \R h\to \R$ such that 
$\varphi_{|U} = \psi$ and $\|\varphi\| = \|\psi\|$. 
:::
<span style="color:green">
Proof idea: write an inequality for the 
value of $\psi(h)$. Prove that a valid value exists 
by triangle inequality and boundedness of $\psi$. 
</span>
<details>
<summary>Proof</summary>
We only need to define $\varphi(h) = c\in \R$ and figure 
out a value for $c$ such that $\varphi(f+\alpha h) = \psi(f) + \alpha c$ 
satisfies the norm condition. On one hand, 
$\varphi_{|U} = \psi\implies \|\varphi\| \geq \|\psi\|$. On 
the other hand, $\|\varphi\| \leq \|\psi\|$ requires  $c$ to satisfy
\[ 
    |\psi(f) + \alpha c| = \varphi(f) \leq 
    \|\varphi\| \|f + \alpha h\| \leq \|\psi\| \|f + \alpha h\|, \quad 
    \forall f\in U, \alpha \in \mbb R. 
\] 
Without loss of generality we can set $\alpha=1$ since $f$ is 
rescalable, requiring 
\[ 
    |\psi(f) + c| \leq \|\psi\| \|f + h\|, \quad 
    \forall f\in U, \alpha \in \mbb R. 
\] 
Expanding the absolute value 
\[ 
    -\|\psi\|\|f+h\| - \psi(f) \leq c\leq \|\psi\|\|f+h\| - \psi(f), 
    \quad \forall f\in U
\] 
The equation will be implied by (in fact, about as strong as, 
since $c$ must be uniform 
\[ 
    \sup_f \left[
        -\|\psi\|\|f+h\| - \psi(f)
    \right] \leq \inf_g \left[
        \|\psi\|\|g+h\| - \psi(g)
    \right]
\] 
To prove this, first note the triangle inequality 
$-\|f+h\| \leq \|g+h\| - \|g-f\|$, then 
\begin{align}
    -\|\psi\|\|f+h\| - \psi(f) 
    &\leq \|\psi\|(\|g+h\| - \|g-f\|) - \psi(f) \\ 
    &\leq \|\psi\|(\|g+h\| - \|g-f\|) + \psi(g-f) - \psi(g)\\
    &=\|\psi\|\|g+h\| - \psi(g) + \left[\psi(g-f) - \|\psi\|\|g-f\|\right]_{\leq 0} \\ 
    &\leq \|\psi\| \|g+h\| - \psi(g)
\end{align}
</details>

:::{.definition #functionGraph name="graph of a function"}
Given a function $T:V\to W$, the graph $\mrm{graph}(T)$ of $T$ IS 
\[ 
    \mrm{graph}(T) = \{(f, T(f):f\in V\}\subset V\times W
\] 
:::

Properties of functions can be read from the graph: 

1. $T$ is a linear map iff $\mrm{graph}(T)$ is a subspace of $V\times W$. 
2. $T:V\to W$ is an extension of $S:U\to W$ iff $\mrm{graph}(S)\subset \mrm{graph}(T)$. 
3. Given a linear map $T:V\to W$, then $\|T\|\leq c$ iff 
    $\|g\| \leq c\|f\|$ for all $(f, g) \in \mrm{graph}(T)$. 

:::{.theorem #hahnBanach name="Hahn-Banach theorem"}
Given a normed vector space $V$ with subspace $U$ 
a bounded linear functional $\psi\in U^*$, then 
there exists $\tilde \psi\in V^*$ with $\|\tilde \psi\|_V = \|\psi\|_U$ 
and $\tilde \psi_{|U} = \psi$. 
:::
<details>
<summary>Proof</summary>
We prove the theorem for the real case. 
Let $\mca A$ be the collection of subsets $E\subset V\times \R$ satisfying: 

1. $E=\mrm{graph}(\varphi)$ for some linear functional $\varphi$ 
    on some subspace of $V$. 
2. $\mrm{graph}(\psi)\subset E\iff \varphi$ is an extension of $\psi$. 
3. $\psi$ generating $E$ has norm at most $\|\psi\|$. 

Then $\mca A$ satisfies the hypothesis of Zorn's lemma \@ref(lem:zorn): 
for every chain of subsets, their union is also in $\mca A$. 
The extension lemma \@ref(lem:extLemma) 
guarantees that the maximal element is the graph 
of a linear functional defined on all of $V$. 
</details>

The next proposition anticipates 
the variational formula of the $p$-norm 
(proposition \@ref(prp:variationalPnorm). 

:::{.proposition #normVariation name="variational formula of the norm"}
Given a normed vector space $V$ and $0\neq f\in V$, 
\[ 
    \|f\| = \sup_{\|\varphi\|_{V^*} = 1} |\varphi(f)|
\] 
In other words, there exists $\varphi\in V'$ 
with $\|\varphi\|=1$ such that $\|f\| = \varphi(f)$. 
:::
<details>
<summary>Proof</summary>
Consider the $1$-dimensional subspace spanned by $f$, 
and define $\psi(\alpha f) = \alpha \|f\|$, 
which on this subspace satisfies $\|\psi\|=1$ and $\psi(f)=\|f\|$. 
Apply the Hahn-Banach extension. 
</details>

## Banach theorems {#banachSpace -}

:::{.definition name="completeness, Banach space"}
A metric space is complete if every Cauchy sequence 
in the space converges. A Banach space is 
a complete normed metric space. 
:::

:::{.proposition #completeInheritance name="connection between complete and closed metric spaces"}
A complete subset of a metric space is closed, and a closed 
subset of a complete metric space is complete. 
:::
<details>
<summary>Proof</summary>
Given a complete subset $V$ of a metric space, every convergent 
sequence is also a convergent Cauchy sequence whose limit 
stays inside $V$. Given a closed subset, the convergent 
limit of every Cauchy sequence must say within $V$ by closure 
property, so $V$ is complete. 
</details>

Recall that to argue for Cauchy convergence we can 
drop to subsequences (proposition \@ref(prp:cauchySubsequence)). 

:::{.proposition name="characterization of Banach space"}
A normed vector space $V$ is complete (i.e. a Banach space) 
iff $\sum_{k=1}^\infty g_k$ converges for every sequence 
$g_j\in V$ satisfying $\sum_{k=1}^\infty \|g_k\|<\infty$. 
:::
<details>
<summary>Proof</summary>
Given $V$ complete, the partial sum of $g$ is a Cauchy 
sequence thus converges. Conversely, 
given a Cauchy sequence, drop to a subsequence $f_j$ 
and set $f_0=0$ so that  
\[ 
    \sum_{k=1}^\infty \|f_k - f_{k-1}\| < \infty 
\] 
then by assumption 
$\sum_{k=1}^\infty (f_k - f_{k-1})=\lim_{n\to \infty} f_n$ 
exists. 
</details>

:::{.proposition #banachDualInheritance name="Banach dual space"}
$\mca B(V, W)$ is a Banach space (under the operator norm) 
if $W$ is a Banach space. In particular, the dual space 
of a Banach space is a Banach space. 
:::
<details>
<summary>Proof</summary>
Given a Cauchy sequence $T_j\in \mca B(V, W)$, for every function 
$f\in V$, the sequence $T_j f\in W$ is a Cauchy sequence; define 
$T\, f = T_{j\to \infty}\, f$. It is linear and bounded, 
so it remains to show that $\lim_{k\to \infty} \|T_k - T\| = 0$. 
This follows from 
\[ 
    \|(T_j - T)\, f\| = \lim_{k\to \infty} \|T_j f - T_k f\|
\]  
</details>

:::{.theorem #baire name="Baire's theorem"}
Given a Banach space: 

1. the intersection of countably many dense open sets is nonempty. 
2. if $X$ is the countable union of 
    closed subsets $G_1, \cdots$, then some $G_j$ 
    contains an open ball. 
:::
<span style="color:green">
Proof idea: for (1), by denseness construct a Cauchy sequence; 
argue (2) by contradiction.
</span>
<details>
<summary>Proof</summary> 
We prove first prove (1): 
given a countable sequence of dense open sets $U_j$, 
we want to show that $\bigcap_{k=1}^\infty U_k \neq \infty$. 

1. Choose $f_1\in U_1$ and $r_1\in (0, 1)$ with 
    $\bar B_{r_1}(f_1)\subset U_1$ (denoting closure). 
2. For each $j$, choose $0<r_j<1/j$, $\bar B_{r_j}(f_j) \subset U_j$ 
    and $\bar B_{r_j}(f_j)\subset \bar B_{r_{j-1}}(f_{j-1})$. 
    We can do this because, fixing $r_{j-1}, f_{j-1}$, the ball 
    $B_{r_{j-1}}(f_{j-1})\cap U_j$ is a nontrivial (by $U_j$ dense) 
    open set, from which we can choose $f_j$ and the radius 
    such that $\bar B_{r_j}(f_j)\subset U_{j-1}$. 
3. Then $f_j$ is naturally a Cauchy sequence because 
    $|f_{j>N} - f_{k>n}| < 1/N$. 

By completeness, $f_j\to f\in X$, completing the proof of (1). 
To prove (2) suppose for contradiction that $X=\bigcup G_j$, 
each of which has empty interior, then $U_j = G_j^c$ 
is open and dense; by (1) there exists 
$f\in \bigcap (G_j^c) = (\bigcup G_j)^c$, contradicting $\bigcup G_j=X$. 
</details>

:::{.corollary #uniformBounded name="principle of uniform boundedness"}
Given $\mca A\subset \mca B(V, W)$ with 
$V$ Banach and $W$ normed satisfying pointwise boundedness 
(below), then $\sup_{T\in \mca A} \|T\|<\infty$. 
\[ 
    \sup_{T\in \mca A} \|Tf\| < \infty, \quad \text{ for every } f\in V 
\] 
:::
<details>
<summary>Proof</summary> 
Given our hypothesis, $V_n\nearrow V$ with 
\[ 
    V_n = \{f\in V: \|T\, f\|\leq n, \quad \forall T\in \mca A\}
\] 
Moreover, $V_n$ is closed since each $T$ is continuous. 
By Baire's theorem there exists $n, h\in V, r>0$ 
with $B_r(h)\subset V_n$. For any $g\in V$ with $\|g\|<1$, 
we have $rg+h\in B_r(h)\subset V_n\implies \|T(rg+h)\|\leq n$. 
\[ 
    \|Tg\| = \left\| 
        \df{T(rg + h)}{r} - \df{Th}{r}
    \right\| \leq \df{\|T(rg+h)\|}{r} + \df{\|Th\|}{r} 
    \leq \df{n+\|Th\|}{r}, \quad \forall g\in V
\] 
Taking $\sup$ over all $T$ completes the proof. 
</details> 

:::{.theorem name="open mapping theorem"}
Given Banach spaces $V, W$, a surjective 
bounded linear map $T:V\to W$ is open (i.e. 
sends open sets to open sets); 
note that this does not require $T$ injective, 
so $T$ is not guaranteed to be a homeomorphism. 
:::
<span style="color:green">
Proof idea: Show that $0\in \mrm{int}\, T(B(0, 1))$. 
Do this by constructing, for each $g\in B(0, 1)\subset W$, 
a bounded $f\in V$ 
(which is the limit of a Cauchy sequence) 
s.t. $g=T\, f$. 
Next use linearity to extend to all open balls. 
</span>
<details>
<summary>Proof</summary>
Given open $U\subset V$, we need to show that 
$\forall f\in U$ such that $B(f, a)\subset U$, 
there exists $b<a$ such that, by linearity 
\[ 
    T\, B(f, b) = T\, f + bT(B) \subset T\, U 
\] 
<span style="color:green">
It thus suffices to show that 
$\exists r: B(0, r)\subset T(B)$ 
</span>
(i.e. $0$ is an interior point of $T(B)$). 
Surjectivity and linearity of $T$ implies that 
\[ 
    W = \bigcup_{k=1}^\infty T(kB) 
    = \bigcup_{k=1}^\infty k T\, B 
\] 
Apply Baire's theorem to $k \overline{T\, B}$ 
and use linearity (which respects closure) 
shows that $\overline{T\, B}$ has a nonempty interior; 
this is where we use the Banach condition on $W$.  
We need to be especially careful when working with 
closure and interiors of infinite-dimensional spaces. 
Given $T\, g_{\in B}\in \mrm{int}\, {\overline{T\, B}}$, 
\[ 
    0 \in \mrm{int}\, \overline{T\, (B - g)} 
    \subset \mrm{int} \, 2\, \overline{T\, B}
    \implies \overline{B(0, \exists r)}
    \subset \overline{T\, B}
\] 
<span style="color:green">
We proceed to show that 
this implies $0\in \mrm{int}(T\, B)$; 
</span>
again, this is not a trivial argument. 
By definition of closure, $\forall h\in W$ 
with $\|h\|\leq r$ we have 
\[ 
    \forall \epsilon>0, \exists f\in B: 
    \|h - T\, f\| < \epsilon 
\] 
Substitute $h\mapsto rh/\|h\|$ yields, 
$\forall h\in W-\{0\}, \epsilon>0$ 
\[ 
    \exists f\in \df{\|h\|}{r}B: 
    \|h - T\, f\|<\epsilon 
    (\#eq:openMappingIter)
\] 
Now pick arbitrary $g\in B\subset W$. 
Apply equation \@ref(eq:openMappingIter) 
with $(h, \epsilon)\mapsto (g, 1/2)$ to obtain 
\[ 
    \exists f_1\in B/r: \|g - T\, f_1\|<1/2 
\] 
Apply equation \@ref(eq:openMappingIter) again 
with $h\mapsto g - T\, f_1\in B/2, \epsilon = 1/4$ to 
obtain 
\[ 
    \exists f_2\in B/2r: \|g - T\, f_1 - T\, f_2\| < 1/4 
\] 
Repeat this construction inductively to obtain 
$f_1, f_2, \cdots \in V$ and let 
\[ 
    f = \sum_{k=1}^\infty f_k, \quad 
    \|f\|\leq \sum_{k=1}^\infty \|f_k\| 
    \leq \sum_{k=1}^\infty \df 1 {2^{k-1}r} = \df 2 r 
\] 
Here we used the Banach condition on $V$. 
By construction, $\|g-T\, f\| < 2^{-n}$ for every $n$, 
then by continuity of $T$ we have $g=T\, f$. 
Thus $T\, B(0, 2 / r)\subset B(0, 1)\implies B(0, r / 2)\subset T\, B$.
</details>

:::{.corollary name="bounded inverse theorem"}
Given $T\in \mca B(V, W)$ injective (so that $T^{-1}$ exists) 
and surjective, 
$T^{-1}$ is a bounded linear map $W\to V$. 
:::

Given two Banach spaces $V, W$ their vector space product 
$V\oplus W$ is a Banach space when equipped with the norm 
$\|(f, g)\| = \max(\|f\|, \|g\|)$. This induces 
the product topology: a product sequence 
converges iff each component converges. 

:::{.theorem #closedGraph name="closed graph theorem"}
Given Banach spaces $V, W$ and $T:V\to W$, then $T$ 
is a bounded linear map iff $\mrm{graph}(T)\subset V\times W$ 
is closed. 
:::
<details>
<summary>Proof</summary>
Given $T$ continuous, given $(f_j, T\, f_j)\in \mrm{graph}(V\times W)$ 
converging to $(f, g)\in V\times W$, by the product topology 
this implies $(f, T\, f)\in \mrm{graph}(T)$, 
which establishes closure of the grpah. Conversely, 
given the graph a closed subspace, it is a Banach space 
(proposition \@ref(prp:completeInheritance)) with the inherited norm. 
Consider the bijective projection map $\pi:\mrm{graph}(T)\to V$ 
with $\pi(f, T\, f) = f$, then 
$\|\pi(f, T\, f)\|\leq \|(f, T\, f)\|$ 
thus is bounded. Apply the bounded inverse theorem 
to obtain that $\pi^{-1}(f) = (f, T\, f)$ is bounded, 
implying 
\[ 
    \|T\, f\| \leq \|(f, T\, f)\| = \|\pi^{-1}(f)\| 
    \leq \|\pi^{-1}\|\|f\|
\] 
Thus $\|T\| \leq \|\pi\|^{-1}$, establishing 
the boundedness of $T$. 
</details>

## Kolmorogorov-Arnold theorem {-}

Let $\mbb I$ denote the compact interval $[0, 1]$ 
and $C(\mbb I)$ the Banach space of continuous 
functions $\mbb I\to \R$ equipped with the supremum norm 
\[
    \|f\| = \sup_{x\in [0, 1]} |f(x)|
\]
Completeness follows from the completeness of $\R$ 
and uniform continuity on a compact interval. 
We also equip $C(I)^n$ with the following norm 
\[
    \|f\in C(I)^n\| = \max_{j\in [n]} \|f_j\|
    (\#eq:productIntNorm)
\]

:::{.lemma #qCoeffs name="rational-distinguishing coefficients"}
For each $n\in \mbb N$ there exist real numbers 
$\lambda_1, \cdots, \lambda_n\in \R$ such that 
for all $x_1, \cdots, x_n, y_1, \cdots, y_n\in \mbb Q$,
\[
    \sum_j \lambda_j x_j = \sum_j \lambda_j y_j \implies 
    x_{\forall j} = y_j 
\]
:::
_Proof:_ Choose $\lambda_j$ to be linearly independent 
over $\mbb Q$. 

To reduce clutter, given a choice of coefficients 
$\lambda\in \R^n$ and embeddings $\phi\in C(\mbb I)^n$, 
define the separately-continuous 
embedding functions $\Phi_j: \mbb I^n\to \R$ by 
\[
    \Phi_j(x_1, \cdots, x_n) 
    = \sum_{j=1}^n \lambda_j \phi_j(x_j)
    (\#eq:embeddingShorthand)
\]


:::{.lemma name="approximate embeddings are dense open subset"}
Fixing $\lambda$ satisfying lemma \@ref(lem:qCoeffs) 
and $f\in C(\mbb I^2)$ with $\|f\|=1$, let 
$U_f\subset C(\mbb I)^5$ consist of tuples 
$(\phi_1, \cdots, \phi_5)\in C(I)^5$ satisfying 

- $\exists g\in C(\R) \text{ such that } \|g\|\leq \df 1 7$, and 
- $\displaystyle \forall x, y\in I^2: \left|
            f(x, y) - \sum_{j=1}^5 (g\circ \Phi_j)(x, y)
        \right| < \df 7 8$, with $\Phi_j$ defined 
    as in equation \@ref(eq:embeddingShorthand). 
    
Then $\forall f\in C(\mbb I^2)$, the set $U_f$ of embeddings 
which allow $g$-approximations of $f$ 
is a _dense open_ subset of $C(\mbb I)^5$. 
:::

Proof idea: 
Openness is easy to argue, to open density, fix 
$\phi^0\in C(\mbb I)^n$ and 

1. Create a atrous redundant tiling $R_1, \cdots, R_{2n+1}$ 
    of $\mbb I$, each covering $1/(2n+1)$ of $\mbb I$ 
    with a fine enough resolution. 
2. Choose $\epsilon$-approximation 
    $\phi_j\sim \phi_j^0$ that is constant rational on 
    each tile $R_j$, distinct on the disconnected pieces of 
    $R_j$, and distinct from any $\phi_{k\neq j}$ everywhere 
    on their designated intervals $R_j, R_k$.


Fixing $f, \lambda$, the set $U_f$ is apparantly 
open since the same $g$ which works for $(\phi_j)$ will also 
work for a neighborhood of $(\phi_j)$ by continuity. 
To prove $U_f$ dense, we need to demonstrate: 

- For every $\phi^0_1, \cdots, \phi^0_5\in C(\mbb I)^5$ 
and $\epsilon>0$, there exists $\phi_1, \cdots, \phi_5\in U_f$ 
such that $\|\phi - \phi^0\|<\epsilon$ as in equation \@ref(eq:productIntNorm).

Fixing a positive integer $N$ (we'll specify it later), 
for each $j\in \{1, \cdots, 5\}$ we can consider 
the set of all intervals 
\[
    R_j = \bigcup_{s=0}^{N-1} \left[\df s N, \df{s+1}{N}\right] 
    1_{s\neq j-1\mod 5}, \quad j\in \{1, \cdots, 5\}
\]
Let $R_{jk}$ denote the almost-disjoint subintervals 
in the union, we call each $R_{jk}$ the $k$-th red 
interval of rank $j$. The following properties are satisfied: 

- Each $R_j$ covers at most $4/5$, 
and each $R_{jk}$ covers $4/N$ of $\mbb I$. 
- Almost every $x\in \mbb I$ is contained in at most $3$ 
of the subintervals $R_{jk}$ for distinct $j$'s. 

Fixing $\phi^0\in C(\mbb I)^5$ and $\epsilon>0$, 
there clearly exists $N$ large enough such that 
there exists $\phi \in C(\mbb I)^5$ satisfying: 

1. $\|\phi - \phi^0\| < \epsilon$. 
2. each $\phi_j$ constant and equal to a rational number 
    on each $R_{jk}$.
    - Follows from the arbitrariness of $N$, uniform continuity 
    of $\phi_j^0$, and the density of $\mbb Q\subset \mbb R$. 
3. $\phi_j(R_{jk})\neq \phi_j(R_{jl})$ for $k\neq l$. 
4. $\phi_j(x) \neq \phi_k(z)$ for all $x\in R_j, z\in R_k$. 

In spirit, each $\phi_j$ is responsible for approximating 
$\phi_j^0$ on $R_j$ and is unconstrained elsewhere. 
Next define the red rectangles $r_{jk}$ of rank $j$ 
to be the disconnected components of $R_j\times R_j\subset \mbb I^2$. 

1. The distance between any two points in one $R_{jk}$ is 
    $\leq \sqrt{2\cdot (4/N)^2} = \sqrt{32}/N$. 
2. By construction of $\lambda$ satisfying lemma \@ref(lem:qCoeffs), 
    the contant value 
    \[ 
        \Phi_j(R_{jr}) = \Phi_k(R_{ks}) 
        \implies (j, r) = (k, s)
    \] 