# $L^p$ Spaces 

Key takeaways: 

1. [Convexity](#convexAnalysis): 
    properties of convex functions, Young's inequality, 
    and Jensen's inequality. 
2. [Construction of $L^p$](#LpSpace) as a Banach space:
    Use Holder's and Minkowski's inequalities to 
    establish the Banach property; dual of $L^p$. 

Main results: 

0. Jensen's inequality (theorem \@ref(thm:jensenInequality)): 
    generalizalized property of convexity w.r.t. integration. 
1. $L^p$ space is a Banach space that consists of 
    equivalence classes of a.e. equal functions. 
    - For $p\geq q\geq 1$ and $\mu(\Omega)<\infty$, we have 
        $L^{p} \subset L^q$. 
2. The convexity of $x\mapsto |x|^{p>1}$ and monotonicity in $p$ 
    implies: 
    - Normed vector space properties of $L^p(\Omega)$ holds for $1\leq p\leq \infty$. 
    (proposition \@ref(prp:LpVectorSpace)). 
    - Young's inequality (proposition \@ref(prp:youngInequality)): 
        holds for $1<p<\infty$; it is essentially the quantitative statement of 
        convexity, 
    - Holder's inequality (proposition \@ref(prp:holderInequality)): 
        holds for $1\leq p\leq \infty$, can be saturated by pointwise-saturating 
        Young's inequality for $p\neq 1, \infty$. 
    - Inclusion: $0<p<q<\infty$ and finite $\mu(\Omega)$ implies $L^p \supset L^q$ 
    (proposition \@ref(prp:lPInclusion)). 
    - Variational formula: $\|f\|_p = \sup_{\|g\|_{\bar p}\leq 1} |f\cdot g|$; 
    holds for $1\leq p < \infty$ generally and $p=\infty$ for 
    $\sigma$-finite $\mu$ (proposition \@ref(prp:variationalPnorm)). 
    - Minkowski's inequality (theorem \@ref(thm:minkowskiInequality)) 
        states the convexity of the $L_p$ norm and holds for $1\leq p\leq \infty$. 
3. Young and Holder's inequality are the main tools for applying convexity. 
    <span style="color:green">
    Young's inequality does not hold for $p=1, \infty$. 
    Holder's inequality hold for $p\in [1, \infty]$ 
    although saturation conditions for $p=1, \infty$ does not come from pointwise 
    saturation of Young's inequality. 
    <span>
4. Fatou's lemma \@ref(lem:fatou) is a great tool for demonstrating 
    $p$-norm convergence using pointwise convergence. 

## Convexity {#convexAnalysis -}

:::{.definition name="convex set and function"}
A convex set $K\subset \R^n$ is closed under 
$(x, y)\mapsto \lambda x + \bar y$ 
for all $\lambda \in [0, 1]$. A **convex function** 
on a convex set $K$ is a real-valued function satisfying 
\[ 
    f(\lambda x + \bar \lambda y) 
    \leq \lambda f(x) + \bar \lambda f(y)
\] 
the function $f$ is **strictly convex** at $x$ if the 
inequality is strict for all $y$. 
:::

:::{.proposition}
If $K$ is an open set, then a convex function on $K$ is continuous. 
:::

:::{.definition name="support plane"}
The support plane to a graph of $f:K\to \R$ at 
$x\in K\subset \R^n$ is a plane in $\R^{n+1}$ that 
touches $(x, f(x))$ and that nowhere lies above the graph; 
if the support plane at $x$ is unique, then it is the tangent plane. 
:::
For example, there is no unique support plane at $x=0$ for $|x|$. 
For convex $f$, the existence of a tangent plane is equivalent 
to differentiability. In particular, the tangent plane 
for $y=f(x)$ at $x_0$ has expression 
\[ 
    y - f(x_0) = \nabla f(x_0) \cdot (y - x)
\] 
Thus for general convex functions, for each $x$ there exists 
a vector $V\in \R^n$ such that 
\[ 
    f(y) \geq f(x) + V\cdot (y - x)
    (\#eq:supportingVector)
\] 

:::{.definition name="Hölder conjugate"}
The Hölder conjugate of $p>1$ is given by the equation 
\[ 
    p^{-1} + q^{-1} = 1
\] 
We also denote $q=\bar p$. 
It is oftentimes more convenient to note that 
\[ 
    p = \df q {q - 1} \iff q = \df p {p - 1}
\] 
:::

:::{.proposition #youngInequality name="Young's inequality"}
Given Hölder conjugates $p, q>1$, 
\[ 
    ab \leq \df {a^p}{p} + \df{b^q}{q}, \quad \forall a, b\geq 0
\] 
Equality is saturated when $a^p = b^q$. 
:::
<details>
<summary>Proof</summary>
Consider the convex function $f(a) = \df{a^p}{p}$. 
Its Legendre transform is 
\begin{align}
    g(b) 
    &= \sup_a \left(ab - \df {a^p}{p}\right) 
    = a_*b - \df{a_*^p}{p},\quad a_* = b^{1/(p-1)} \\ 
    &= b^{1 + 1/(p-1)} - \df 1 p b^{p/(p-1)} = b^q - \df 1 p b^q 
    = \df{b^q}{q}
\end{align}
Young's inequality follows from the variational characterization 
of the Legendre transform. 
Equality is saturated when $a=b^{1/(p-1)} \iff a^p = b^q$. 
</details>

:::{.definition name="average of a measurable function"}
Assuming $\mu(\Omega)$ is finite, the expectation (average) of 
a measurable function $f:\Omega\to \R$ is defined as 
\[ 
    \la f\ra = \df 1 {\mu(\Omega)} \int_\Omega f\, d\mu 
\] 
:::

:::{.theorem #jensenInequality name="Jensen's inequality"}
Given a convex function $J:\R\to \R$ and 
measurable $f:\Omega\to \R$ with $\mu(\Omega)<\infty$, then 

1. The negative part $(J\circ f)_-$ is in $L^1(\Omega)$ 
    (recall the decomposition $f=f_+ - f_-$. 
2. $\la J\circ f\ra \geq J(\la f\ra)$; when $J$ is strictly 
convex at $\la f\ra$, there is equality iff $f$ is constant. 
:::
<span style="color:green">
Proof idea: integrate the supporting 
vector equation \@ref(eq:supportingVector). 
</span>
<details>
<summary>Proof</summary>
Fixing $\la f\ra$, there exists a constant $V\in \R$ 
such that 
\[ 
    J(\forall t)\geq J(\la f\ra) + V(t - \la f\ra)
    (\#eq:convexity) 
\] 
This bounds the negative component (but not the positive one!) 
\[ 
    [J\circ f]_-(x) \leq |J(\la f\ra)| + |V||\la f\ra| + |V| |f(x)| 
\] 
using $\mu(\Omega)<\infty$, this bounded function is integrable. 
To obtain (2), integrate \@ref(eq:convexity) for all $t=f(x)$ 
\[ 
    \la J \circ f\ra \geq J(\la f\ra) - V \la f\ra + V\la f\ra 
\] 
with $J$ strictly convex, the inequality is saturated 
when $\la J\circ f\ra = J(\la f\ra)$. 
</details>

## $L^p$ as a Banach space {#LpSpace -}

:::{.definition #LpDef name="Lp space, norm"}
Given a positive (nonnegative) measure 
$\mu$ and $1\leq p<\infty$, the space 
$L^p(\Omega, d\mu)$
is the space of complex-valued functions $f:\Omega\to \mbb C$ 
such that: 

1. $f$ is $\mu$-measurable. 
2. $|f|^p$ is $\mu$-integrable. 

The measure $d\mu$ is usually omitted if understood. 
Given $f\in L^p(\Omega)$, its norm is 
\[ 
    \|f\|_p = \left[\int_\Omega |f(x)|^p \mu(dx)\right]^{1/p}
\] 
This definition is extended to $L^\infty(\Omega, d\mu)$ 
as the space of $\mu$-a.e. bounded functions, with 
\[ 
    \|f\|_\infty = \inf \{
        K: \mu(\{x\in \Omega: |f(x)|>k\}) = 0
    \}
\] 
The $\infty$-norm is also called the **essential supremum** 
of $|f|$. 
:::

:::{.proposition #LpVectorSpace name="normed vector space"}
$L^p(\Omega, d\mu)$ is a vector space, and the $L^p$ norm satisfies
for $1\leq p\leq \infty$:  

a. Linearity: $\|\lambda f\|_p = |\lambda| \|f\|_p$. 
b. Nonnegativity: $\|f\|_p\geq 0$ with equality iff $f=0$ for $\mu$-a.e. 
c. Triangle inequality: $\|f+g\|_p \leq \|f_p\| + \|g\|_p$. 
:::

<details>
<summary>Proof</summary>

- Vector space properties: closure under scalar multiplication is apparant. 
    Closure under addition follows from the convexity of $|x|^p$. 
    \[ 
        \left\|\df{\alpha + \beta}{2}\right\|^p \leq \df{|\alpha|^p + |\beta|^p}{2}
    \] 
    which follows from the convexity of $|x|^p$. 
- Norm properties: linearity follows from definition. 
    For nonnegativity, 
    $\|f\|_p = 0 \iff \|f^p\|_1 = 0 \iff f=0$, where the second and 
    third equalities are to be understood as $\mu$-a.e. 
    Triangle inequality is proved by Minkowski's inequality \@ref(thm:minkowskiInequality). 
</details>

:::{.proposition #holderInequality name="Hölder's inequality"}
Given measurable $f, g$ on $(\Omega, \Sigma, \mu)$ and $p\in [1, \infty]$
\[ 
    \|fg\|_1 \leq \|f\|_p \|g\|_{\bar p}
\] 
:::
<span style="color:green">
Proof idea: normalize $f, g$, then apply Young's inequality. 
</span>
<details>
<summary>Proof</summary>
The cases $p=1$ or $\infty$ is straightforward, so consider $p>1$. 
Consider the nontrivial case where 
$0< \|f\|_p, \|g\|_{\bar p} < \infty$. 
First assume $\|f||_p = \|g\|_{\bar p}=1$, then 
using Young's inequality (proposition \@ref(prp:youngInequality)): 
\begin{align}
    \int |fg|\, d\mu  
    &\leq \int \df 1 p |f|^p + \df 1 {\bar p} \|g\|^{\bar p}\, d\mu 
    = \df 1 {p} + \df 1 {\bar p} = 1
\end{align}
This completes the proof in the special case; for unnormalized 
$f, g$, apply the homogeneity of the norms. 
</details>

:::{.proposition #lPInclusion}
If $\mu(\Omega)<\infty$, then for $0<p<q<\infty$, we have 
\[ 
    \|f\|_p \leq \mu(\Omega)^{(q-p)/pq} \|f\|_q
\] 
and $L^q \subset L^p$. 
:::
<details>
<summary>Proof</summary>
Apply Holder's inequality to $r=q/p>1$: 
\begin{align}
    \|f\|_p^p 
    &= \||f|^p\|_1 
    \leq \| |f|^p\|_{q/p} \|1\|_{\overline{q/p}}  
    = \|f\|_q^p \mu(\Omega)^{(q-p)/q} \\ 
    \|f\|_p 
    &\leq \mu(\Omega)^{(q-p)/pq} \|f\|_q
\end{align}
</details>

:::{.proposition #variationalPnorm name="variational formula for p-norm"}
Given $1\leq p<\infty$ and $f\in L^p$ 
\[ 
    \|f\|_p = \sup_{\|g\|_{\bar p} \leq 1} \|fg\|_1 
\] 
This holds for $p=\infty$ assuming $\sigma$-finite $\mu$. 
:::
<details>
<summary>Proof</summary>
If $\|f\|_p=0$ then both sides are zero trivially. 
The $p=1$ case holds trivially, so first consider $1 < p < \infty$, 
One side of Holder's inequality gives 
\[ 
    \left|\int fg\, d\mu \right| \leq \|fg\|_1 \leq \|f\|_p 
\] 
To prove the other direction, one can choose $\|g\|$ which 
saturates the inequality above by (1) matching the sign of $f$ 
and (2) saturate Young's inequality by $g(x)^{\bar p} = f(x)^p$. 
<span style="color:green">
Note how the converse breaks down for $p=\infty$, in which case
Holder's inequality is not implied by Young's. 
</span>
</details>

:::{.remark name="counterexample"}
For $p=\infty$, consider the non $\sigma$-finite measure 
on $X=\{b\}$ with $\mu(\emptyset)=0, \mu(\{b\})=\infty$. 
Then $L^1=\{0\}$. For the constant function $f=1$, we have 
$\|f\|_\infty = 1$ (recall definition \@ref(def:LpDef) carefully). 
:::

:::{.theorem #minkowskiInequality name="Minkowski's inequality"}
Given $1\leq p \leq \infty$ and 
$f, g\in L^p$, $\|f+g\|_p \leq \|f\|_p + \|g\|_p$. 
:::
<details>
<summary>Proof</summary>
For arbitrary $h\in L^{\bar p}$ with $\|h\|_{\bar p}\leq 1$, we have 
\[ 
    \left|\int (f+g) h\, d\mu \right| 
    \leq (\|f\|_p + \|g\|_p) \|h\|_{\bar p} \leq \|f\|_p + \|g\|_p
\] 
Take supremum over $h$ and invoke the variational formula 
(proposition \@ref(prp:variationalPnorm)) to obtain the desired result. 
</details>

:::{.proposition #LpBanach name="Lp is a Banach space"}
Every Cauchy sequence in $L^p$ converges. 
:::
<span style="color:green">
Drop to a subsequence, use Minkowski's inequality 
to argue absolute convergence, next use Fatou's lemma 
to establish convergence in $p$-norm from a.e pointwise convergence. 
<span>
<details>
<summary>Proof</summary>
First consider $1\leq p<\infty$. 
By proposition \@ref(prp:cauchySubsequence), without loss of 
generality drop to a subsequence $f_j$ (which can be defined 
inductively using the Cauchy condition) and define $f_0=0$ such that 
\[ 
    \sum_{k=1}^\infty \|f_k - f_{k-1}\|_p < \infty
\] 

1. Conditions for the dominated convergence theorem: 
    we aim to show the integrability of
    \[ 
        g_m = \sum_{k=1}^m |f_k - f_{k-1}| \to g \in L^p 
    \] 
    note that $g_m < g$. This follows by Minkowski's inequality 
    (theorem \@ref(thm:minkowskiInequality)) and the definition 
    of our subsequence we have 
    \[ 
        \|g\|_p^p = \int |g|^p\, d\mu 
        = \lim_{m\to \infty} |g_m|^p\, d\mu 
    \] 
    The second equality uses the monotone convergence 
    theorem \@ref(thm:monotoneConvergence). 
2. Next define the partial sum 
    \[ 
        f_m = \sum_{k=1}^m f_k - f_{k-1}
    \] 
    We have $|f_m| \leq g_m$, the absolute convergent 
    sequence $g_m(x)$ (for a.e. $x$)
    also implies the convergence of $f_m(x)\to f(x)$ a.e.
    Then $|f(x)|\leq g(x)\implies f\in L^p$. 
3. Finally, use Fatou's lemma \@ref(lem:fatou)
    to demonstrate convergence in $p$-norm: 
    \begin{align}
        \|f_k - f\|_p = \left(
            \int |f_k - f|^p\, d\mu 
        \right)
        \leq \liminf_{j\to \infty} \left(
            \int |f_k - f_j|^p\, d\mu 
        \right) = \liminf_{j\to \infty} \|f_k - f_j\|_p 
    \end{align}
</details>

## Duality {-}

:::{.definition name="norm of linear functional"}
placeholder. 
:::

:::{.definition name="continuity and boundedness"}
placeholder. 
:::

:::{.theorem #LpDual name="Riesz representation theorem"}
The dual space of $(L^p)$ for $1< p < \infty$ 
is $L^{\bar p}$; every linear functional $L\in L^p(\Omega)^*$ 
has the form, for some unique $v\in L^{\bar p}$, 
\[ 
    L(g) = \int_\Omega v(x)g(x)\, d\mu 
\] 
This is true for $p=1$ if $(\Omega, \Sigma, \mu)$ is $\sigma$-finite. 
The identification $(L^p)^* \cong L^{\bar p}$ is further norm-preserving: 
\[  
    \|L\| = \|v\|_q
\] 
:::