---
title: "Measure Theory, Functional Analysis"
author: "Nicholas Lyu"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [refs.bib]
biblio-style: "numeric"
split_bib: yes
link-citations: true
---

\usepackage{cancel}
\usepackage{amsmath}
\usepackage{bm}
\newcommand{\pd}[1]{\partial_{#1}}

\newcommand{\mbb}{\mathbb}
\newcommand{\mbf}{\mathbf}
\newcommand{\mb}{\boldsymbol}
\newcommand{\mrm}{\mathrm}
\newcommand{\mca}{\mathcal}
\newcommand{\mfk}{\mathfrak}
\newcommand{\tr}{\mrm{tr}} 
\newcommand{\df}{\dfrac}
\newcommand{\la}{\langle}
\newcommand{\ra}{\rangle}
\newcommand{\dag}{\dagger}

\newcommand{\Cl}{\mca C}
\newcommand{\Gr}{\mca G}
\newcommand{\Pf}{\mrm{Pf}}
\newcommand{\Pa}{\mca P}
\newcommand{\R}{\mbb R}
\newcommand{\C}{\mbb C}
\newcommand{\N}{\mbb N}
\newcommand{\F}{\mbb F}
\newcommand{\supp}{\mrm{supp}}

\newcommand{\poly}{\mrm{poly}}



# Preface {-}
These notes accompany the Fall 2024 iteration of Math 114, a second-semester 
undergraduate course on real analysis and measure theory. These notes 
deviate quite a bit from lecture materials, in particular: 

1. I prefer a more principled construction of the Lebesgue measure as the restriction of 
    the exterior measure using the Carathéodory theorem.
    - Sets declared measurable by the Carathéodory criteria are automatically 
    closed under $\sigma$-algebra operations, so 
    one only needs to show the measurability of rectangles 
    to establish the measurability of the Borel sets.
2. Materials are heavily supplemented by Sheldon Axler's 
    _Measure, Integration and Real Analysis_. 
3. Some time is spent on infinite-dimensional vector spaces and 
    results in Banach spaces, since 
    (1) nontrivial complexities arive when we generalize linear algebra 
    constructions to infinite-dimensions, and 
    (2) several theorems are important for convex analysis.
4. Other miscellany:
    - Proof of Young's inequality (proposition \@ref(prp:youngInequality)) 
    using the Legendre transform to highlight the role of convexity. 

## Organization {-}

1. Abstract machinery of [measures and $\sigma$-algebra](#abstractMachinery). 
    - Lieb and Loss, chapter 1. 
2. The [exterior measure and Lebesgue measure](#realMeasures) on $\R^n$. 
    - Hunter. 
3. [Lebesgue integral](#integration), 
    Littlewood's three principles, and integral convergence theorems. 
    - Rudin, , chapter 11; Axler, chapter 2; Lieb and Loss, chapter 1. 
4. [Iterated integrals](#iteratedIntegrals}): uniqueness of product measure 
    and Fubini's theorem. 
    - Lieb and Loss, chapter 1. 
5. [Spaces of functions](#banachSpaces): 
    normed vector spaces, dual space of bounded linear functionals,  
    and the Hahn-Banach theorem; Baire's theorem and other Banach theorems. 
    - Axler, Chapter 6; Luenberger, Chapter 5. 
6. [$L^p$ spaces](#Lpspaces). 
    - Lieb and Loss, chapter 2; Axler, chapter 7. 
5. [Fourier analysis](#Fourier). 
    - Axler, Chapter 11. 

References for these notes

1. Axler, _Measure, Integration \& Real analysis_ [@axler2020measure]. 
2. Lieb and Loss, _Analysis_ [@lieb2001analysis]. 
3. John K. Hunter, [online notes](https://www.math.ucdavis.edu/~hunter/measure_theory/measure_notes_ch2.pdf)
    on the Lebesgue measure. 
4. Rudin, _Principles of Mathematical Analysis_ [@rudin1964principles]. 
5. Luenberger, _Optimization by Vector Space Methods_ [@luenberger1997optimization]. 

## Main deliverables {-}

1. <u>Monotone class theorem</u> \@ref(thm:monotoneClassTheorem): 
    freely-generated monotone class equals freely-generated $\sigma$-algebra 
    for algebra of sets containing $\Omega$. 
2. <u>Carathéodory's theorem</u> \@ref(thm:measureConstruction): 
    given an outer measure $\mu$, the measurable sets $B\subset \Omega$ satisfying 
    $\mu(\forall E) = \mu(E\cap B) + \mu(E\cap B^c)$ form a $\sigma$-algebra 
    and obey countable additivity. 
3. <u>Dominated convergence theorem</u> \@ref(thm:dominatedConvergence): 
    dominated pointwise limit of measurable functions can be exchanged with integral.  
4. <u>Hahn-Banach, hyperplane separation</u> theorems:
    for every extension of a bounded linear functional, there exists a 
    norm-minimizing one which preserves the original norm. 
4. <u>Fubini's theorem</u>
5. <u>Baire's theorem</u> \@ref(thm:baire): for 
    every cover of a complete metric space 
    by closed sets, there exists an element with nonempty interior. 

Proof techniques:

1. Working with countable collection of approximations: given tolerance $\epsilon$, 
    introduce approximation of index $j$ with tolerance $\epsilon 2^{-j}$ 
    to have additively bounded total tolerance. 
    - Examples: outer measure properties of 
    exterior measure (proposition \@ref(prp:extOuterMeasure)). 
2. Prove properties for characteristic functions, then generalize them 
    using approximation and limit theorems [here](#realIntegration). 
    - Examples: Luzin's theorem, 
    monotone convergence theorem \@ref(thm:monotoneConvergence),   
3. Sandwich bounds 
    - Lemma \@ref(lem:caratheodoryAdditive), 
    Monotone convergence theorem. 
4. Argue the convergence of a subsequence satisfying $\sum |f_k - f_{k-1}|<\infty$ 
    when working with Cauchy sequences. 
    - Baire's theorem \@ref(thm:baire). 
    Completeness proof for $L^p$ (proposition \@ref(prp:LpBanach)). 
5. Prime example for the use of monotone convergence theorem, Fatou's lemma, 
    and dominated convergence theorem: proposition \@ref(prp:LpBanach). 
6. Using the monotone class theorem (example theorem \@ref(thm:uniqueMeasure)): 
    rewrite nested chain as disjoint union, then pass through the limit 
    using the countable additivity of measures. 
    Next apply the reduction from finite to $\sigma$-finite measures. 
7. Demonstrating a certain property (e.g. triviality): approximate by 
    a tractable dense subset. 
    - Orthonormality of the Fourier basis on $L^2(\partial D)$
    (proposition \@ref(prp:discBasis)). 


Mandatory todo list: 

0. Inductive generalization of Holder's inequality. 
1. Put in some pset problems. 
1. Pset problem: separately continuous implies measurable. 
3. Dual of $L^p$ space. 

Optional: 

2. Lieb and Loss 2.9 to 2.18: compactness under weak convergence. 
1. Product measures and Fubini. 
3. Arnold-Kolmorogorov theorem. 